### ISSUE TITLE
Null reference exception for EventHandler property with name starting with "Item"

### ISSUE THREAD

**Issue by kaan-kaya** [moq/moq4#869] opened 2019-08-05 14:57 UTC
I have experienced an issue when trying to mock an interface with a EventHandler property whose name starts with "Item".

Sample interface:

```
public interface IEventGenerator
{
    EventHandler<BaseCustomEventArgs> ItemAdded { get; set; }
}
``

**Comment by stakx** [comment] 2019-08-05 15:57
@kaan-kaya, could you please provide a minimal but complete code example that we can run to reproduce that exception? Otherwise I'll close this issue in a few days'time.

**Comment by stakx** [comment] 2019-08-06 05:45
This is very likely a duplicate of #870, so I am also closing this. If you think that was in error, please let me know and we'll reopen.

**Closed by stakx** 2019-08-06 05:45 UTC
Labels: duplicate, needs-repro
