### ISSUE TITLE
  Callback not beeing called in current version 4.2.1506.2016  

### ISSUE THREAD

**Issue by BitKFu** [Moq/moq4#183] opened 2015-06-23 11:18 UTC
**What steps will reproduce the problem?**

I'm mocking a async WCF call the following way
```C#
svc.Setup(s => s.BeginStartWorkTimeLogging(It.IsAny<TpAuthentication>(), It.IsAny<Guid>(), It.IsAny<Guid?>(), It.IsAny<Guid?>(), It.IsAny<string>(), It.IsAny<DateTime?>(), It.IsAny<AsyncCallback>(), null))
                .Callback<TpAuthentication, Guid, Guid?, Guid?, string, DateTime?, AsyncCallback, object>(
                    (auth, projectId, taskId, customerId, description, logonTime, callback, state) =>
                    {
                        callback(aresult);
                    })
                .Returns(aresult);
svc.Setup(s => s.EndStartWorkTimeLogging(out fault, out todayEntries, It.IsAny<IAsyncResult>()))
               .Returns(activeTimeEntry);
```

**What is the expected output? What do you see instead?**

The expected behaviour is that the callback method is beeing called. **Such is working through Version 4.2.1502.911 of MOQ**

Starting with Version 4.2.1506.2016 the callback method won't be called anymore. The test runs without any technical exception, but it fails because the callback method won't be called. 

**What version of the product are you using? On what operating system?**

I'm using the .NET Framework 4.52

**Please provide any additional information below.**

The strange Thing is, that I have several tests that Mocks different WCF calls. But only some are failing because of the callback not beeing called.

**Comment by rbirkby** [comment] 2015-06-24 08:43
According to #184, this appears to be caused by the nullable types. I'm seeing the same behavior.

**Comment by pkpjpm** [comment] 2015-06-25 05:29
[PR 185](https://github.com/Moq/moq4/pull/185) should close this

**Comment by kzu** [comment] 2015-06-25 15:55
PR merged and nuget pushed. Plz verify if the issue is fixed and close if so?

Tnx!

**Comment by rbirkby** [comment] 2015-06-25 16:05
About 1% of our tests were failing with 4.2.1506.2016.
Now with the new build (from nuget), they all succeed. Thanks

**Comment by kzu** [comment] 2015-06-25 16:51
yay! :)

**Closed by kzu** 2015-06-25 16:51 UTC

**Comment by BitKFu** [comment] 2015-06-25 20:30
Thanks, will try it asap.
