### ISSUE TITLE
System.ArgumentException : Invalid callback. Setup on method with 0 parameter(s) cannot invoke callback with different number of parameters (1)

### ISSUE THREAD

**Issue by Saibamen** [moq/moq4#579] opened 2018-01-20 16:28 UTC
In my test I get error described in this issue title:

```
mockedUserRepository.Setup(r => r.GetAll())
                .Returns(new List<DataAccess.Models.User> { user1, user2 }.AsQueryable);
```

My code for this Setup:

`var userList = userRepository.GetAll().Where(x => users.Contains(x.Id)).ToList();`

Moq 4.8.1. When I was using 4.7.145 everything was OK.

**Comment by stakx** [comment] 2018-01-20 16:38
Possibly a duplicate of #572.

**Comment by Saibamen** [comment] 2018-01-20 17:16
@stakx https://github.com/Saibamen/BriskChat/blob/4fe6d36f68bc25f2cb3367d6950169903cee6a4c/TrollChat.BusinessLogic.Tests/Actions/Room/AddNewPrivateConversationTests.cs#L63

**Comment by stakx** [comment] 2018-01-20 17:31
Sorry, but please post minimal but complete (self-contained) repro code here.

**Closed** 2018-01-30 21:05 UTC
Labels: needs-repro, unresolved

**Comment by neurohunter** [comment] 2018-06-26 14:14
`using System;
using NUnit.Framework;
using Moq;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var a = new A();
            Console.WriteLine(a.DoTheThing("thing"));
            Console.ReadKey();
        }
    }


    [TestFixture]
    public class AFixture
    {
        [Test]
        public void DoTheThingTest()
        {
            // this test fails with Invalid callback error
            var a = Mock.Of<IA>();
            var aMock = Mock.Get(a);
            aMock.Setup(i => i.DoTheThing(It.IsAny<string>())).Returns<string>(v => "Not A Thing");
        }

        [Test]
        public void DoAThing()
        {
            // This test passes
            var a = Mock.Of<IA>();
            var aMock = Mock.Get(a);
            aMock.Setup(i => i.DoAThing()).Returns<string>(v => "Not A Thing");
        }
    }

    public interface IA
    {
        string DoAThing();
        string DoTheThing(string a);
    }


    public class A : IA
    {
        public string DoAThing()
        {
            return "A Thing Default";
        }

        public string DoTheThing(string a)
        {
            return "The Thing" + a;
        }
    }
}
`

**Comment by stakx** [comment] 2018-06-26 16:06
@neurohunter - Could you perhaps explain what your post above is about?

**Comment by neurohunter** [comment] 2018-06-26 16:15
@stakx I found this issue with Invalid callback in Moq in my project, found this issue discussion here and noticed that it was closed because no reproduction scenario is provided. So I've basically appended the scenario that I've used to represent the issue.

**Comment by stakx** [comment] 2018-06-26 16:36
@neurohunter, OK thanks! I didn't look above your post, I just saw a block of code without any explanation so I was confused enough already to not even look any further. Sorry for that. :smile:

**Comment by stakx** [comment] 2018-06-26 16:42
@neurohunter - I'm a bit confused however. The test that you've marked as `// This test passes` fails, and the one you've marked with `// this test fails with Invalid callback error` passes. Also, I have no clue what the `Main` method is supposed to do...?

**Comment by neurohunter** [comment] 2018-06-26 16:45
@stakx Yes, you're right, I've added comments later by hand and, apparently, mixed things up. 
The correct snippet looks like this:
```csharp
using System;
using NUnit.Framework;
using Moq;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var a = new A();
            Console.WriteLine(a.DoTheThing("thing"));
            Console.ReadKey();
        }
    }

    [TestFixture]
    public class AFixture
    {
        [Test]
        public void DoTheThingTest()
        {
            // This test passes
            var a = Mock.Of<IA>();
            var aMock = Mock.Get(a);
            aMock.Setup(i => i.DoTheThing(It.IsAny<string>())).Returns<string>(v => "Not A Thing");
        }

        [Test]
        public void DoAThing()
        {
            
            // this test fails with Invalid callback error
            var a = Mock.Of<IA>();
            var aMock = Mock.Get(a);
            aMock.Setup(i => i.DoAThing()).Returns<string>(v => "Not A Thing");
        }
    }

    public interface IA
    {
        string DoAThing();
        string DoTheThing(string a);
    }


    public class A : IA
    {
        public string DoAThing()
        {
            return "A Thing Default";
        }

        public string DoTheThing(string a)
        {
            return "The Thing" + a;
        }
    }
}
```
Main method is not supposed to do anything, it's just there.

**Comment by stakx** [comment] 2018-06-26 16:50
OK, in that case this is simply caused by the documented change as mentioned in the changelog:

> ## 4.8.0-rc1 (2017-12-08)
> #### Changed
> * Delegates passed to Returns are validated a little more strictly than before (return type and parameter count must match with method being set up) (@stakx, #520)

This was requested by #445.
