### ISSUE TITLE
AddRangeAsync xunit .net core error

### ISSUE THREAD

**Issue by zaiboot** [moq/moq4#327] opened 2017-03-06 03:56 UTC
Running on:
* VS2017 
* .net core 1.1
* moq 4.7.1
* xunit 2.2.0-beta5-build3474
* xunit.runner.visualstudio : 2.2.0-beta5-build1225

I have the following code on my repositoryfile.cs
```csharp
public async Task<int> AddSales(IList<SomeModel> mode)
{
    await Context.DBSet.AddRangeAsync(model);
    return await Context.SaveChangesAsync();
}
```

And the following test:

```csharp
[Fact]
public async void AddSalesTest()
{
    var expected = 1;
    var sales = new List<SomeModel>
    {
        new SomeModel{ ... }
    };
    _context.Setup(c => c.DBSet.AddRangeAsync(It.IsAny<List<SomeModel>>(), It.IsAny<CancellationToken>()));
    _context.Setup(c => c.SaveChangesAsync(It.IsAny<CancellationToken>())).ReturnsAsync(expected);
    var system = GetSystem();
    var actual = await system.AddSales(sales);
    Assert.Equal(expected, actual);
}
```
Getting the following error:

> Message: Moq.MockException : DbSet`1.AddRangeAsync([Reporting.DAL.Models.SomeModel], System.Threading.CancellationToken) invocation failed with mock behavior Strict.
> Invocation needs to return a value and therefore must have a corresponding setup that provides it.

Seems like Moq doesnt support mocking `Task` vs `Task<OfSomething>`.

Any ideas on this? If you need more info I can set up a git repo to show the error in a more easy way.

Thanks

**Comment by stakx** [comment] 2017-06-05 20:11
@zaiboot: Your code won't compile since it's incomplete so it's hard to reproduce your issue, but I guess this part of the error message is a sufficient hint at what is going wrong here:

> ….AddRangeAsync(…) invocation failed with mock behavior Strict.
> Invocation needs to return a value and therefore must have a corresponding setup that provides it.

This tells you that the first of your two setups (the one involving `AddRangeAsync`) is incomplete; it is lacking a `.Returns`. As I understand it, `MockBehavior.Strict` requires every `.Setup` to have a `.Returns`:

> ```csharp
> _context.Setup(c => c.DBSet.AddRangeAsync(It.IsAny<List<SomeModel>>(), It.IsAny<CancellationToken>()));
> ```

If you add a `.Returns(…)`, the error should go away:

```csharp
_context.Setup(c => c.DBSet.AddRangeAsync(…))
        .Returns((List<SomeModel> _, CancellationToken __) => Task.FromResult(true));
```

(Tried this the latest version of Moq, which is 4.7.25.)

**Comment by stakx** [comment] 2017-06-05 20:53
I do wonder, though, whether there should be a `.SetupAsync(Expression<Func<T, Task>>)` that doesn't require a `.Returns`.

* While it's true that async methods (should) return at least a `Task`, and if they have a return value then there must be a `.Returns` &mdash...
* However, methods returning `Task` are really the asynchronous counterpart to `void` methods, and those do *not* require a `.Returns`.

**Comment by stakx** [comment] 2017-06-21 08:04
I am closing this for now, since we have no working repro code and the reported error is quite possibly due to incorrect usage (see [this comment further above](https://github.com/moq/moq4/issues/327#issuecomment-306291458)).

Regarding [my previous comment just above](https://github.com/moq/moq4/issues/327#issuecomment-306305885), I think this would be better tracked in #384.

@zaiboot: If the above does not help you, please report back and we take another look at your issue.

**Closed by stakx** 2017-06-21 08:04 UTC

**Comment by stakx** [comment] 2017-12-28 23:13
This is quite likely a minimal repro code example for this issue:

```
public interface IFoo
{
    Task DoAsync();
}

var mock = new Mock<IFoo>(MockBehavior.Strict);
mock.Setup(m => m.DoAsync());
await mock.Object.DoAsync();
```

As noted above, one could argue that there should be a `Mock<T>.SetupAsync(Expression<Func<T, Task>>)` method such that async methods can be set up without specifying `.Returns`.
