### ISSUE TITLE
It.IsAnyType not working for Func returning Task with generic type

### ISSUE THREAD

**Issue by Ansssss** [moq/moq4#1040] opened 2020-07-16 20:36 UTC
I believe this is a bug. Originally posted on [stackoverflow](https://stackoverflow.com/questions/62940053/moq-it-isanytype-not-working-for-func-returning-task-with-generic-type).

Note this seems very close to the issue [918](https://github.com/moq/moq4/issues/918), but I see that one is closed and I'm still seeing this issue with Moq version 4.14.0.0.

I've tried 3 different ways to setup a mock for a generic interface method. Only one way works, but it is using an explicit type, so won't work generically. I tried using It.IsAnyType, but it doesn't seem to match on the call that is made.

Here is the sample code (I expected test case 1 to have "asdf" returned). How can I get the mock to work for any type (not just string?)?

```C#
using Moq;
using System;
using System.Threading.Tasks;

namespace blah
{
    public class Junk : IGetOrAddable
    {
        public static void Main()
        {
            Test(1);
            Test(2);
            Test(3);
            /*********OUTPUT*********
            For test case 1, value is null
            For test case 2, value is asdf
            Unhandled exception. System.ArgumentException: Object of type 
                'System.Func`2[System.Object,System.Threading.Tasks.Task`1[System.String]]'
                cannot be converted to type 
                'System.Func`2[System.Object,System.Threading.Tasks.Task`1[Moq.It+IsAnyType]]'.
            *************************/
        }

        public static void Test(int testCase)
        {
            Mock<IGetOrAddable> mock = new Mock<IGetOrAddable>();

            //setup the mock to always call the valueFactory function (ignore cache)
            switch(testCase)
            {
                case 1:
                {
                    //use the It.IsAnyType to match any generic invocation of this method
                    mock.Setup(x => x.GetOrAdd<It.IsAnyType>(It.IsAny<object>(), It.IsAny<Func<object, Task<It.IsAnyType>>>()))
                        .Returns((object k, Func<object, Task<It.IsAnyType>> f) => f(k));
                    break;
                }
                case 2:
                {
                    //use an exact type (string?) to match a specific type invocation of this method
                    mock.Setup(x => x.GetOrAdd<string?>(It.IsAny<object>(), It.IsAny<Func<object, Task<string?>>>()))
                        .Returns((object k, Func<object, Task<string?>> f) => f(k));
                    break;
                }
                case 3:
                {
                    //try casting It.IsAny<object> per this suggestion: https://stackoverflow.com/a/61322568/352349
                    mock.Setup(x => x.GetOrAdd<It.IsAnyType>(It.IsAny<object>(), (Func<object, Task<It.IsAnyType>>)It.IsAny<object>()))
                        .Returns((object k, Func<object, Task<It.IsAnyType>> f) => f(k));
                    break;
                }
            }
            
            var value = mock.Object.GetOrAdd<string?>(new object(), RetrieveCoolValue).Result;
            Console.WriteLine($"For test case {testCase}, value is {value ?? "null"}");
        }
        public Task<T> GetOrAdd<T>(object key, Func<object, Task<T>> valueFactory)
        {
            //complicated cache retrieval stuff here of the sort described in https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd?view=netcore-3.1
            throw new NotImplementedException();
        }
        public static Task<string?> RetrieveCoolValue(object key)
        {
            return Task.FromResult<string?>("asdf");
        }
    }

    public interface IGetOrAddable
    {
        Task<T> GetOrAdd<T>(object key, Func<object, Task<T>> valueFactory);
    }
}
```

**Comment by stakx** [comment] 2020-08-01 16:24
Pretty sure this is a duplicate of #919, given that your example uses `It.IsAnyType` as a nested part of another type (`Task<It.IsAnyType>`), support for which isn't implemented yet (like those other issues mention).

**Comment by weitzhandler** [comment] 2020-09-18 13:24
I think it's safe to close this one.

**Closed** 2020-09-27 17:56 UTC
Labels: duplicate
