### ISSUE TITLE
Possible regression between 4.7.49 and 4.7.58?

### ISSUE THREAD

**Issue by sharky98** [moq/moq4#383] opened 2017-06-21 01:08 UTC
I've created a piece of code, based on article [Entity Framework Testing with a Mocking Framework (EF6 onwards)](https://msdn.microsoft.com/en-us/data/dn314429(v=vs.113)). Where I'm bugging is in the Testing query scenarios section.

I was using version 4.7.49 and I had to modify the `mockSet.As<IQueryable<Blog>>().Setup(m => m.GetEnumerator()).Returns(0 => data.GetEnumerator());` to `mockSet.As<IQueryable<Blog>>().Setup(m => m.GetEnumerator()).Returns(data.GetEnumerator());` to make it work. The test was running fine. When I updated Moq to 4.7.58, the test is failing with following error:

> Message: Test method TestSuites.Models.TypeTests.FindAll threw exception: 
System.NotImplementedException: The member 'IEnumerable<TResult>.GetEnumerator' has not been implemented on type 'DbSet`1Proxy' which inherits from 'DbSet`1'. Test doubles for 'DbSet`1' must provide implementations of methods and properties that are used.

I'm new to the C#, ASP.NET MVC, EF world, so I'm a bit lost on where to look for my error.

Here my test method, if that make any differences:

```c#
        /// <summary>
        /// Find All
        /// </summary>
        [TestMethod]
        public void FindAll()
        {
            // Mocking the set and context
            // [...]

            // Create fake data
            IQueryable<Type> data = new List<Type>
            {
                new Type { TypeId= 1, Name = "Test A", Slug = "test-a", Format = "dollar" },
                new Type { TypeId= 2, Name = "Test B", Slug = "test-b", Format = "percent" },
                new Type { TypeId= 3, Name = "Test C", Slug = "test-c", Format = "dollar" },
            }.AsQueryable();

            // Setup the IQueryable on the mockRateTypeSet
            mockTypeSet.As<IQueryable<RateType>>().Setup(m => m.Provider).Returns(data.Provider);
            mockTypeSet.As<IQueryable<RateType>>().Setup(m => m.Expression).Returns(data.Expression);
            mockTypeSet.As<IQueryable<RateType>>().Setup(m => m.ElementType).Returns(data.ElementType);
            mockTypeSet.As<IQueryable<RateType>>().Setup(m => m.GetEnumerator()).Returns(data.GetEnumerator());

            // Find all
            List<Type> types = typeRepository.FindAll().ToList();

            // Asserts
            Assert.AreEqual(3, rateTypes.Count());
            Assert.AreEqual("Test Rate A", rateTypes[0].Name);
            Assert.AreEqual("Test Rate B", rateTypes[1].Name);
            Assert.AreEqual("Test Rate C", rateTypes[2].Name);
        }
```

**Comment by stakx** [comment] 2017-06-21 06:06
Thanks for reporting. Unfortunately, I cannot get your repro code to run, since some type declarations and variable definitions are missing. Could you please provide a short but complete repro code so I can look into it? Thanks!

**Comment by vascofernandes** [comment] 2017-06-21 10:25
Same exact problem.

Regards

**Comment by stakx** [comment] 2017-06-21 13:14
Thank you @vascofernandes for the repro code.

This is indeed a regression introduced by #381 (which itself fixed a major regression that has been lurking around for ages).

I should have a fixed version of Moq available later today.

**Comment by stakx** [comment] 2017-06-21 16:50
This (or at least the problem reported by @vascofernandes) should be fixed in Moq 4.7.63.

**Closed by stakx** 2017-06-21 16:50 UTC

**Comment by vascofernandes** [comment] 2017-06-22 13:14
Confirmed. It is fixed. 
Thanks a lot.

Regards

**Comment by stakx** [comment] 2017-06-22 14:09
Glad to hear!
