### ISSUE TITLE
Retrieving object of Mock object with stubbed virtual protected property fails with Mono 5.4.0.201

### ISSUE THREAD

**Issue by gabsima-nexapp** [moq/moq4#481] opened 2017-10-10 16:41 UTC
Since we updated our version of Visual Studio for Mac to 7.2 (including an update to Mono 5.4.0.201) all of our tests that stubs a virtual property fails when we extract the object out of the Mock.

<img width="973" alt="screen shot 2017-10-10 at 12 35 30 pm" src="https://user-images.githubusercontent.com/32681197/31398678-bdf63c2a-adb7-11e7-9c56-c2b6d710e936.png">

Here is the stacktrace : 
https://gist.github.com/gabsima-nexapp/f405c0ecde752fc578d57c6dcff72401

Line 32 of the stack trace corresponds to the last line of my screenshot.

**Comment by stakx** [comment] 2017-10-10 17:46
Thanks for the report. May I ask, what is the actual exception thrown, and the exception message?

**Comment by gabsima-nexapp** [comment] 2017-10-10 17:51
I'm affraid i don't have more information than the stack trace... It seems that Mono is having a SIGABRT when Moq tries to create a proxy.

**Comment by stakx** [comment] 2017-10-10 18:56
What version of Moq are you using? Have you tried any other (older) versions? If not, could you please try to find the first version of Moq that breaks your tests in the way you reported?

**Comment by gabsima-nexapp** [comment] 2017-10-10 19:02
We have Moq version 4.7.137. I'm going to try with older versions.

**Comment by gabsima-nexapp** [comment] 2017-10-10 20:45
We've been able to use a previous version of the Mono framework (5.2.0) and our tests are now working like before the update. It seems to be a compatibility problem between Moq and the latest version of Mono.

**Comment by stakx** [comment] 2017-10-10 20:46
> The only version i found where the problem is unexistant is with 3.1.416.3.

(I am going to assume that you didn't artificially pin Castle Core to version 4.2.0 while you ran your Moq downgrade experiment.)

That version is several years old. If there were such an grave problem in Moq such that it could no longer deal with virtual methods, then that would've been discovered long, long ago. I hate to tell you the obvious, but I am reasonably sure the problem is in your environment, not Moq.

> Since we updated our version of Visual Studio for Mac to 7.2 (including an update to Mono 5.4.0.201) all of our tests that stubs a virtual property fails when we extract the object out of the Mock.

Is it possible for you to install the version of Mono you used previously, then run your tests using it?

**Comment by stakx** [comment] 2017-10-10 20:52
@gabsima-nexapp - I suppose it would be good if you checked whether this problem has already been [reported with Mono](http://www.mono-project.com/community/bugs/); and if not, I'm sure they would appreciate your bug report.

Is there anything else that you feel should be done from Moq's side, or can we close this issue?

**Comment by gabsima-nexapp** [comment] 2017-10-10 20:55
Thank you, it seems it has already been logged in mono's bugzilla. Thanks for the support!

**Closed** 2017-10-10 20:57 UTC
Labels: invalid

**Comment by SittenSpynne** [comment] 2017-10-12 20:34
@gabsima-nexapp Could you link to that issue in mono's bugzilla? I can't seem to find it and I'd like to follow it.

**Comment by gabsima-nexapp** [comment] 2017-10-12 20:38
Sure, here it is https://bugzilla.xamarin.com/show_bug.cgi?id=29953
