### ISSUE TITLE
Setup/Verifyable With Times

### ISSUE THREAD

**Issue by BlythMeister** [moq/moq4#530] opened 2017-11-23 15:21 UTC
Would it be possible to provide a setup with an expected number of times the execution occurs.

And then use verifyable and verify all to ensure that it was executed the correct number of times.

This would work in a similar way to RhinoMocks with

```
var mock = MockRepository.GenerateStrictMock<IDoStuff>();
var sut = new FunctionRunner(mock);

mock.Expect(x => x.DoFunction()).Return(true).Repeat.Once;
mock.Expect(x => x.DoFunction()).Return(false).Repeat.Times(5);

sut .Execute();

mock.VerifyAllExpectations();
```

There is 2 reasons why you might want to do this.

1) You might want a different result on the 1st call to all subsequent calls
2) If your function takes a number of parameters, you don't need to specify a setup and verify which can be very verbose.

Currently in moq you would need to:
```
var mock = new Mock<IDoStuff>(MockBehavior.Strict);
var sut = new FunctionRunner(mock.Object);

var calls = 0;
mock.Setup(x => x.DoFunction()).Returns(calls==0).Callback(() => calls++);

sut .Execute();

mock.Verify(x => x.DoFunction(), Times.Exactly(6));
```

If DoFunction took a lot of parameters, or something which is verbose, that's a lot of copied data between the setup and verify, just to make sure it was called x times and returned the right values on each of the 6 calls (true the first time, and false the other 5 times)

If this could be simplified to

```
var mock = new Mock<IDoStuff>(MockBehavior.Strict);
var sut = new FunctionRunner(mock.Object);

mock.Setup(x => x.DoFunction(), Times.Exactly(1)).Returns(true);
mock.Setup(x => x.DoFunction(), Times.Exactly(5)).Returns(false);

sut .Execute();

mock.VerifyAll();
```

**Comment by stakx** [comment] 2017-11-23 17:24
Duplicate of #373.

**Comment by BlythMeister** [comment] 2017-11-23 17:36
@stakx sorry,  i didn't search closed issues :(

as an asside, for anyone else who comes here, this is my workaround/hack which is a superclass of a Mock<T> which implments a setup and saves the verify to be called as part of the verify all.
Joining the 2 processes together in a single setup call :)

```
public class MyMock<T> : Mock<T> where T : class
    {
        private readonly List<Action> verifyFunctions;

        public MyMock()
        {
            verifyFunctions = new List<Action>();
        }

        public ISetup<T> Setup(Expression<Action<T>> action, Times times)
        {
            var setup = Setup(action);
            verifyFunctions.Add(() => Verify(action, times));
            return setup;
        }

        public new void VerifyAll()
        {
            base.VerifyAll();
            foreach (var verifyFunction in verifyFunctions)
            {
                verifyFunction();
            }
        }
    }
```

**Comment by BlythMeister** [comment] 2017-11-23 20:51
@stakx having read through #373 I actually don't believe this is a duplicate as the reasoning behind this is not the same.

The point I am trying to make is 2 fold.

The first is the ability to specify a return to only occur X number of times.
Therefore giving the ability to specify different returns on the exact same function call whereby the variance is the number of times executed.

The second is the ability to chain a setup with a verify in a single statement.
Therefore preventing the requirement to specify the mock expression multiple times (once on the setup, and once on the verify)
This reduces the amount of test code and potential rework should you need to refactor function parameters

**Comment by stakx** [comment] 2017-11-24 00:24
I don't believe the suggested syntax would be a very good fit with Moq's current API. It would basically turn everything into sequences. (And there are already two mechanisms for that, `MockSequence` and `SetupSequence`&mdash;did you look at those?)

The syntax you're suggesting (`Times` parameter to `Setup` meaning that the setup will expire after that amount of calls) would very likely be very difficult if not impossible to implement because (a) noone says that `Times` is required to be a continuous range of numbers in theory, and (b) it interferes with Moq's principle that a setup with an identical call expression as another, precdding setup overrides that setup).

I don't see any way to implement your suggestion. I think we'd do better to focus on making Moq's sequence features (e.g. `SetupSequence`) more useful.

**Closed by stakx** 2017-11-24 00:24 UTC
Labels: enhancement

**Comment by BlythMeister** [comment] 2017-11-24 10:11
@stakx i didn't know about SetupSequence, that does exactly what i wanted for half of this issue :)

The other half is essentially this.
Is there a way to simplify this example
```
[TestFixture, Parallelizable(ParallelScope.All)]
    public class MockupTests
    {
        public interface IDoStuff
        {
            void Execute(string key, string key2, string key3, string key4, string key5);
        }

        public class TestSystem
        {
            private readonly IDoStuff doStuff;

            public TestSystem(IDoStuff doStuff)
            {
                this.doStuff = doStuff;
            }

            public void TestFunction()
            {
                doStuff.Execute("Testing", "Testing2", "Testing3", "Testing4", "Testing5");
            }
        }

        private Mock<IDoStuff> mock = new Mock<IDoStuff>(MockBehavior.Strict);
        private TestSystem sut;

        [SetUp]
        public void Setup()
        {
            sut = new TestSystem(mock.Object);
        }

        [Test]
        public void Test()
        {
            mock.Setup(x => x.Execute(It.Is<string>(v => Equals(v, "Testing")), It.Is<string>(v => Equals(v, "Testing2")), It.Is<string>(v => Equals(v, "Testing3")), It.Is<string>(v => Equals(v, "Testing4")), It.Is<string>(v => Equals(v, "Testing5"))));

            sut.TestFunction();

            mock.Verify(x => x.Execute(It.Is<string>(v => Equals(v, "Testing")), It.Is<string>(v => Equals(v, "Testing2")), It.Is<string>(v => Equals(v, "Testing3")), It.Is<string>(v => Equals(v, "Testing4")), It.Is<string>(v => Equals(v, "Testing5"))), Times.Once);
        }
    }
```
having the setup and verify lines being 90% the same, but verify having the extra condition just seems very verbose and this feels a bit wrong

```
[Test]
        public void Test2()
        {
            Expression<Action<IDoStuff>> mockEx = x => x.Execute(It.Is<string>(v => Equals(v, "Testing")), It.Is<string>(v => Equals(v, "Testing2")), It.Is<string>(v => Equals(v, "Testing3")), It.Is<string>(v => Equals(v, "Testing4")), It.Is<string>(v => Equals(v, "Testing5")));

            mock.Setup(mockEx);

            sut.TestFunction();

            mock.Verify(mockEx, Times.Once);
        }
```

**Comment by stakx** [comment] 2017-11-24 11:05
@BlythMeister - #527 is discussing a possibility of avoiding repetition in setup / verification expressions.

Apart from that, the easiest way of avoiding identical setup and verification expressions would be to use a loose mock instead of a strict mock (if that's acceptable in your situation), because then you might not need the setup at all and would only be left with the verification expression.

**Comment by BlythMeister** [comment] 2017-11-24 11:14
ok, i'll keep an eye out for #527 thanks.

And yeah, my second example was the not very elegant scenario.
Obviously, it's also possible to do what i suggested earlier in the thread and extend the Mock class
