### ISSUE TITLE
After updating moq from 4.10.1 to 4.11, mocking nhibernate session throws a System.NullReferenceException.

### ISSUE THREAD

**Issue by ronenfe** [moq/moq4#955] opened 2019-10-24 11:05 UTC
```
 public class UnitTest1
    {
        [Fact]
        public void TestMethod1()
        {
            // Arrange
            Guid itemId = Guid.NewGuid();
            var session = new Mock<NHibernate.ISession>();
            var repo = new Repository();
            session.Setup(x => x.QueryOver<Item>().Where(b => b.Id == itemId).List()).Returns(new List<Item>());

            // Act
            var res = repo.GetById(itemId, session.Object);

            // Verify
            //...
        }
    }
  class Repository
    {
        public IList<Item> GetById(Guid id, ISession session)
        {
            var items = session.QueryOver<Item>()
                .Where(b => b.Id == id)
                .List();

            return items;
        }
    }
    public class Item
    {
        public Guid Id { get; set; }
    }
```
4.11 and above:
getting: System.NullReferenceException: 'Object reference not set to an instance of an object.'

![image](https://user-images.githubusercontent.com/8763689/67504757-af680a00-f692-11e9-9f5b-47e357a7db8a.png)

4.10.1 and beyond:
works.

Attached is a sample solution. See exception when running the test. Downgrade to 4.10.1 and see error is gone.
[UnitTestProject2.zip](https://github.com/moq/moq4/files/3768511/UnitTestProject2.zip)

**Comment by stakx** [comment] 2019-10-24 11:53
... and what would _"doesn't work"_ mean exactly? Sorry, your report doesn't make it clear enough what exactly the problem is.

**Comment by ronenfe** [comment] 2019-10-24 11:57
I am revising the report but couldn't delete it, give me a while for analyzing.

**Comment by ronenfe** [comment] 2019-10-24 16:13
Hi, I edited the description and attached a sample solution.

**Comment by ronenfe** [comment] 2019-10-25 07:41
Same error for latest version of Moq.

**Comment by stakx** [comment] 2019-10-25 10:40
Thanks for the repro, @ronenfe. This does look like a regression. Seems like quoted expressions might no longer be treated correctly in all cases. I'll take a closer look soon.

**Comment by stakx** [comment] 2019-10-26 19:00
@ronenfe, not a regression, after all! Starting with Moq 4.11.0, matching of multi-part expressions such as your `x => x.QueryOver<Item>().Where(b => b.Id == itemId).List()` has become more accurate, in earlier versions Moq didn't really match arguments correctly&mdash;now it does, and finds that `b => b.Id == itemId` from your test and `b => b.Id == id` inside your repository class are not equal LINQ expression trees. That in turn is due to captured variables (`itemId` and `id`), which haven't been evaluated prior to expression tree comparison.

I'll need to check whether it makes sense to evaluate captured variables prior to comparing the expression trees; if yes, your use case can likely be fixed; otherwise, I'll close this issue.

**Comment by ronenfe** [comment] 2019-10-28 11:27
Thanks stakx, is it possible to overcome this with the current version by changing the usage?  or I need to wait for next release?

**Comment by stakx** [comment] 2019-10-28 11:37
> is it possible to overcome this with the current version by changing the usage?

Yes, although the resulting code will be less semantically correct than what you have now. You simply need to make sure that you pass the same (as in `object.ReferenceEquals`) `Expression<Func<Item, bool>>` to both `.Where(...)` calls. That is, create that expression once, store it to a variable that's accessible to both code sites, then use it in both places.

**Comment by ronenfe** [comment] 2019-10-28 14:02
I added the expression to the Item class as a property but I also had  to extract the itemId to a property as I can't create an expression without having an id variable when creating it.
If you have bettdr suggestion please let me know, these are the changed class and test:
`
using System;
using System.Collections.Generic;
using Moq;
using Xunit;


namespace UnitTestProject2
{
    public class UnitTest1
    {
        [Fact]
        public void TestMethod1()
        {
            // Arrange
            Guid itemId = Guid.NewGuid();
            var session = new Mock<NHibernate.ISession>();
            var repo = new Repository();
            session.Setup(x => x.QueryOver<Item>().Where(repo.Expression).List()).Returns(new List<Item>());

            // Act
            var res = repo.GetById(itemId, session.Object);

            // Verify
            //...
        }
    }
}
`
`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
using NHibernate;

namespace UnitTestProject2
{
    class Repository
    {
        public Guid ID { get; set; } = new Guid();
        public Expression<Func<Item, bool>> Expression;


        public Repository()
        {
            Expression = b => b.Id == ID;
        }
        public IList<Item> GetById(Guid id, ISession session)
        {
            ID = id;
            var items = session.QueryOver<Item>()
                .Where(Expression)
                .List();

            return items;
        }
    }
}
`

**Comment by dawncold** [comment] 2019-11-25 13:55
I found the latest Moq (4.13.1) will return `null` if your return type is `IList`; will return the correct type if your return type is `IEnumerable`, others may be correct, I haven't tested.


```csharp
public class SomeType
    {
        public string Name { get; set; }
    }
public interface ISomething
    {
        public IEnumerable<SomeType> ListTypesIEnumerable();
        public IList<SomeType> ListTypesIList();
    }

var mockedSomething = new Mock<ISomething>();

var resultOfIEnumerable = mockedSomething.Object.ListTypesIEnumerable();
Console.WriteLine($"Moq(IEnumerable): {resultOfIEnumerable.GetType()}");

var resultOfIList = mockedSomething.Object.ListTypesIList();
Console.WriteLine($"Moq(IList) is null: {resultOfIList is null}");
```

Is it related?

**Closed** 2020-04-18 17:31 UTC
Labels: enhancement

**Comment by stakx** [comment] 2020-04-18 17:33
There you go @ronenfe&mdash;starting with the next version of Moq (4.14.0), your scenario should once again work like it used to.
