### ISSUE TITLE
4.13.0 Breaks Json Serialization on Mock<T>().Object

### ISSUE THREAD

**Issue by ristogod** [moq/moq4#940] opened 2019-10-16 18:08 UTC
All of our unit tests used to work until we upgraded to Moq 4.13.0.

We traced down one of the issues being that a mocked object used to be able to be serialized by Newtonsoft and now it can't. I've reproduced the issue in this gist.

[https://gist.github.com/ristogod/83273f8659d0b249fe30d44feee6677d](https://gist.github.com/ristogod/83273f8659d0b249fe30d44feee6677d)

We tried this and it seemed allow serialization to work, but broke other stuff. So we aren't convinced this is a good idea.

``` csharp
new Mock<T>().As<ISerializable>()
             .As<T>()
             .Object;
```

**Comment by stakx** [comment] 2019-10-17 06:38
Thanks for reporting.

Let me first ask one thing about your test code: So previously (in 4.12.0) serialization of mocks with JSON.NET worked... but did you actually look at the produced JSON? It would be over 185,000 lines long. Is that *really* what you want? What does one actually *do* with such a horrific chunk of garbage JSON?

That aside, serialization is a somewhat difficult topic, as many serializers have the ability to serialize objects even when they aren't marked `[Serializable]` (as is the case with e.g. `Mock<T>`). This apparently leads people to believe that *every* object should be serializable.

Moq objects currently aren't, and AFAICT never were, `[Serializable]` (except for `MockException`). Making them serializable would require quite a bit of effort to ensure that only safe fields get serialized across the whole object graph, and that a new proxy object gets instantiated upon de-serialization.

Before anyone has to do all that work, I would like to ask you to consider why you want to serialize mocks in the first place. I already alluded to it above, but to me it seems like you might be doing serialization incorrectly. Being able to serialize random objects may be convenient (as long as it works), but perhaps it would be better to define truly serializable DTO types and map your (possibly non-serializable) objects to them (and vice versa) using tools like AutoMapper before and after serializing the former?

**Comment by stakx** [comment] 2019-10-17 18:58
For the record, this "break" happened because [this private field](https://github.com/moq/moq4/blob/cfb10decabccba4117f6ecc875d887bb7ccd4680/src/Moq/Invocation.cs#L17) and [this internal property](https://github.com/moq/moq4/blob/cfb10decabccba4117f6ecc875d887bb7ccd4680/src/Moq/Invocation.cs#L67) were added to the internal `Invocation` type in commit 1ffe0ed0ea56a6df9580e196b89200da4d8cf622.

We *could* "fix" this by marking the `Invocation` type as `[DataContract]`, the added field as `[NonSerialized]` and the added property as `[IgnoreDataContract]`, this would seem like a rather random countermeasure, and incorrect, too: `Invocation` is not a data contract.

This underlines what I said above... adding these internal bits to a non-serializable type should be considered benign and shouldn't matter to the outside world.

**Comment by stakx** [comment] 2019-10-17 19:00
@ristogod, if you really must serialize mocks, you should be able to get things working again by adding one more converter to your serializer settings:

```csharp
jsonSerializerSettings.Converters.Add(new InternalAssemblyBuilderToDummyValueConverter());
// ...

class InternalAssemblyBuilderToDummyValueConverter : JsonConverter
{
    public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
    {
        JToken t = JToken.FromObject(new { WARNING = "not serializable" });
        t.WriteTo(writer);
    }

    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) => throw new InvalidOperationException();

    public override bool CanRead => false;

    public override bool CanConvert(Type objectType) => objectType.FullName == "System.Reflection.Emit.InternalAssemblyBuilder";
}
```

I'm going to close this particular issue as "won't fix" since I do not see this as a regression. If you believe that mocks should be generally serializable, I would appreciate if you could state your "pro" arguments in a new, more general issue about mock serializability so the community can discuss it as a proposal.

**Closed by stakx** 2019-10-17 19:00 UTC
