### ISSUE TITLE
MissingMethodException / "Method not found" after update to Moq 4.8.0

### ISSUE THREAD

**Issue by JHotterbeekxBannerconnect** [moq/moq4#566] opened 2018-01-03 12:41 UTC
Hi,

Today I've tried updating the NuGet package from 4.7.145.0 to 4.8.0.0 and I'm running into an issue with a specific test case failing now on a strange error message. To give you some context, in our tests we create a HttpActionContext to test our authentication. This is native .net functionality. I've isolated the issue to the following code:

    [Test]
    public void OnActionExecuting_ShouldFillMarketInSession() {
      var fakeActionContext = _CreateFakeHttpActionContext();
    }

    private HttpActionContext _CreateFakeHttpActionContext() {
      return new HttpActionContext(null, new ReflectedHttpActionDescriptor()) {
        Response = new HttpResponseMessage(HttpStatusCode.OK)
      };
    }

When running this test, it fails with the following error:

> System.MissingMethodException : Method not found: 'Void System.Web.Http.Controllers.HttpActionContext.set_Response(System.Net.Http.HttpResponseMessage)'.
   at SMP.Api.Test.Filter.MoqTest._CreateFakeHttpActionContext()
   at SMP.Api.Test.Filter.MoqTest.OnActionExecuting_ShouldFillMarketInSession() in C:\Projects\Athena\Athena\SMP.Api.Test\Filter\MoqTest.cs:line 14

Could you help me figure out what is wrong, or fix this if it is an actual bug?

Thanks,
John

**Comment by stakx** [comment] 2018-01-03 12:47
I see nothing related to Moq in your example code. Could you please provide a short but complete code example that demonstrates this issue?

**Comment by willykc** [comment] 2018-01-03 13:18
Hi, I think I'm seeing the same problem. Out of 405 tests using Moq, 16 started failing after upgrading to Moq 4.8.0 with exception "System.MissingMethodException: Method not found". It seems to be related to the "System.Net.Http" namespace since all the "missing methods" in the failing tests have types from that namespace in their signature (eg. "System.Net.Http.HttpResponseMessage").

**Comment by stakx** [comment] 2018-01-03 14:01
@JHotterbeekxBannerconnect, @willykc: Could it be that you updated not just Moq, but any other Microsoft ASP.NET packages at the same time without noticing it? Because quite frankly, Moq has no dependency on, nor any special logic related to, any `System.Net.Http.*` types. I don't see how this issie could be caused by Moq, especially given that the exception gets triggered in a piece of code that doesn't even involve Moq.

**Comment by JHotterbeekxBannerconnect** [comment] 2018-01-04 06:46
We've updated several packages, but saw tests failing. So I reverted everything and updated one by one, everything keeps working until the last package is updated, which is Moq. But I'm going to try cleaning old DLL's and cache and see what that does, and if it still doesn't work try a new solution to reproduce this.

**Comment by stakx** [comment] 2018-01-04 06:57
@JHotterbeekxBannerconnect: That's truly strange. Until you have repro code ready to share, could you perhaps give the following information:

* What version of Visual Studio are you working with?
* What exact framework / platform are your projects targeting?
* What NuGet packages (including version numbers) are your projects referencing?
* Are you using `<PackageReference>`s or a NuGet `packages.config`?
* Are there any assembly binding redirects in your App.config or Web.config? If so, what do they look like?

**Comment by JHotterbeekxBannerconnect** [comment] 2018-01-04 07:27
@stakx I've been able to reproduce it in a simple test project: 
[Working.without.Moq.zip](https://github.com/moq/moq4/files/1602660/Working.without.Moq.zip)

When you open this (in VS 2017) you'll see that there is one single test in there. This runs without any issues. Now try adding through NuGet, you'll see that the test fails. 

I've found something more interesting, when updating to the latest version of Moq through NuGet, another package seems to come along called **System.Threading.Tasks.Extensions.4.4.0**. This is the one that seems to be causing the error, because if I remove this as reference from the included test project, the test will succeed again.

The other info you requested (for the test solution):
- VS 2017 Professional 15.5.2 / .net v 4.7.02556
- Any CPI
- Just Moq 4.8.0
- packages.config
- None

Hopefully this is enough for you to reproduce it.

**Comment by stakx** [comment] 2018-01-04 07:44
Thanks a lot for the test solution, and the analysis you've done already!

One problem I'm noticing before I can even run your tests is that your project is referencing a missing `System.Web.Http` assembly:

![system-web-http-not-found](https://user-images.githubusercontent.com/104481/34554074-544cb1fc-f12b-11e7-821b-01aa4fda0b8d.png)

A NuGet restore doesn't help here, since there doesn't seem to be a NuGet package in `packages.config` which might include this assembly.

Given that you're having issues with `Http` types, I find that rather suspicious.

I'll now try to fix and then reproduce your exact issue.

**Comment by stakx** [comment] 2018-01-04 08:11
OK, seems you're affected by the problem described in https://github.com/dotnet/standard/issues/481, and adding the following to your `MoqTests.csproj` file appears to resolve the issue:

```xml
<PropertyGroup>
  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
</PropertyGroup>
```

The problem indeed gets triggered by `System.Threading.Tasks.Extensions` package (which Moq references because of `ValueTask<TResult>`). Note that it does not target the full .NET Framework, only .NET Standard. Referencing a .NET Standard assembly from a .NET Framework project used to not work, but support for doing just that was added in .NET 4.6.1. Unfortunately, it's a pretty flaky feature. See the linked issue for details.

**Comment by JHotterbeekxBannerconnect** [comment] 2018-01-04 08:19
@stakx Thanks a lot for the help and explanation! I've added the properties to the solution and the tests run without any issue now. Seems like something that more people could run into, maybe this should be put in the wiki somewhere?

**Comment by stakx** [comment] 2018-01-04 08:25
@JHotterbeekxBannerconnect - I agree that this situation needs to be improved. I'm currently looking into Moq's reference of the `System.Threading.Tasks.Extensions` package (which was added in 2194e5fe). It doesn't seem right that this package is referenced at all by the `net45` target, as this framework version didn't yet allow references to .NET Standard assemblies. And then there's that issue I linked to to deal with.

Adding a warnign to the wiki would be a start... would you like to do this?

Short of temporarily removing `ValueTask<TResult>` support in Moq for the full .NET Framework, I'm not sure how to cleanly resolve this problem.

I'm also still not sure yet why just referencing that assembly caused the issue (note that your test doesn't make use of it).

**Comment by JHotterbeekxBannerconnect** [comment] 2018-01-04 08:47
@stakx I've added it as a FAQ to the wiki, referencing to the .net standard issue and this issue. Great that you'll look in to this, I agree that it feels weird that this issue is being caused, and even stranger without actually using anything from the reference.

**Comment by willykc** [comment] 2018-01-04 08:55
Hi @stakx, thanks a lot for the solution. After adding the property group to my test project file, all the failing tests are now passing.

I'm not sure if this could help but an idea would be to add a .props file including the property group to the Moq NuGet package like so: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package

**Comment by JHotterbeekxBannerconnect** [comment] 2018-01-04 09:24
@stakx It seems that the adding of a .net standard reference was also causing issues on our TeamCity servers, which we had to resolve as well by updating the build tools and adding .net Core support. Just telling you because this could become an issue for more people.

**Comment by stakx** [comment] 2018-01-04 10:26
@JHotterbeekxBannerconnect, thanks a lot for setting up the FAQ! It's great to have such a resource that we can direct people to. :+1:

@willykc, that's good to know&mdash;thanks for the link. However, I don't feel too comfortable about Moq influencing the build process behind the user's back. Moq is just a library and just one out of many possible dependencies a project might have. Imagine the potential complications if every dependency secretly modified your build. Some people might not actually want to have assembly binding redirects generated automatically.

I believe the problem should be solved at the source, if possible. And I suspect it's that that the build process picks the wrong assembly version from the `System.Threading.Tasks.Extensions` package (starting with .NET 4.6.1, it can pick either the .NET Standard assembly, or the Portable Class Library assembly, the latter of which is probably the right one to pick). I'll try to figure out the exact circumstances under which this problem appears.

If all else fails, I'm quite ready to temporarily remove `ValueTask<TResult>` support from Moq so people don't run into this while we find a permanent solution.

I'll keep you updated!

**Comment by AdamDotNet** [comment] 2018-01-04 16:09
@stakx 
My understanding is that, it's not .Net 4.6.1 that enabled referencing .Net Standard libraries, it's that .Net 4.6.1 was the lowest version that works with .Net Standard 2.0 specifically. The tooling (VS) helps you reference .Net Standard libraries, not necessarily the Framework you are targeting.

The [System.Threading.Tasks.Extensions](https://www.nuget.org/packages/System.Threading.Tasks.Extensions/) NuGet has a dependency on .Net Standard 1.0, the lowest common denominator. Microsoft's [documentation on .Net Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) states that a 1.0 library is compatible with .Net Framework 4.5. Therefore, it shouldn't be a problem to have the net45 TFM reference the System.Threading.Tasks.Extensions NuGet. Visual Studio / NuGet.exe should pick up the "most correct" version of the NuGet when multiple targets are available.

However, it is possible to only reference the NuGet on a specific TFM, and then #if out the relevant code if that's what you want. In fact, the [Moq CSProj already does that](https://github.com/moq/moq4/blob/cf10cdb0f220eb3551a8dc451ac94a6f0dc06439/Source/Moq.csproj#L43).

For what it's worth, I just tried the following sample code on a .Net 4.5 console app without any compilation, or runtime issues; using VS 2017 15.5.2.

``` csharp
using Moq;
using System;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    public interface IFoo
    {
        ValueTask<string> Bar();
    }

    class Program
    {
        static async Task Main(string[] args)
        {
            Mock<IFoo> mock = new Mock<IFoo>();
            mock.Setup(m => m.Bar()).ReturnsAsync("Hello world");

            string bar = await mock.Object.Bar();
            Console.WriteLine(bar);
        }
    }
}
```

Does this answer your questions?

**Comment by stakx** [comment] 2018-01-04 21:21
Let me summarize my findings regarding `MissingMethodException`s in Moq 4.8.0. Below, you'll find:

1. a very minimal test project which reproduces the issue;
2. an explanation of what exactly triggers it; and
3. a description of how to resolve this issue.

(I originally wanted to include a rant about .NET Core, .NET Standard, and NuGet having put us back firmly in DLL hell, and about the continually sorry state of .NET tooling surrounding those three; but anyone working with .NET who hasn't lived under a rock in the past few years probably knows that already, so I've edited it out. 😜)

### 1. Test project that reproduces a `MissingMethodException`:

Download it here: [MinimalRepro.zip (1.4 KB)](https://github.com/moq/moq4/files/1604470/MinimalRepro.zip).

![minimalrepro](https://user-images.githubusercontent.com/104481/34580618-ec92b90e-f18d-11e7-86a1-286dc7e69768.png)

Please note:

* Does not reference Moq. Because Moq isn't actually to blame. :sunglasses:
* There is a warning about an assembly version conflict, and a hint about adding a `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` property to the project file. Depending on the way how you set up your own projects, you might or might not see something similar.

## 2. Why is the `MissingMethodException` occurring?

* The test project targets the full .NET Framework (4.6.1, but the exact version is perhaps unimportant).
* We are referencing the `System.Threading.Tasks.Extensions` NuGet package, presumably because we'd like to use `ValueTask<>` somewhere in our project.
* That package does not explicitly have an assembly for that target. Among other targets, it supports Portable Class Library profile 259 (which includes .NET 4.5) and .NET Standard 1.0. Visual Studio / MSBuild will pick the latter.
* Referencing a .NET Standard assembly (`System.Threading.Tasks.Extensions`) from a .NET Framework project (`MinimalRepro`) implies that during a build, a whole lot of supporting .NET Standard assemblies will be copied to the output directory&mdash;regardless of whether we actually use the .NET Standard library or not. Because of that copying, our `MinimalRepro`'s output directory will now have a .NET Standard `System.Net.Http` assembly, version 4.2.0.0.
* The `Microsoft.AspNet.WebApi.Core` NuGet package however references the target framework's `System.Net.Http` version 4.0.0.0 (against which it was compiled).
* Our own code references stuff from both `System.Net.Http` version 4.2.0.0 (`HttpResponseMessage`) and from `Microsoft.AspNet.WebApi.Core` (`HttpActionContext`).
* Thus both versions 4.0.0.0 and 4.2.0.0 are referenced and we have a version conflict which will eventually surface as the `MissingMethodException`.

My personal conclusion is that `System.Net.Http` or some of the ASP.NET assemblies are versioned incorrectly. https://github.com/aspnet/Hosting/issues/926#issuecomment-276674380 hints at the same thing ("...some of the ongoing issues with the System.Net.Http packages...").

## 3. How can I resolve this problem?

[As mentioned above](https://github.com/moq/moq4/issues/566#issuecomment-355222021), try adding this to your `.csproj` or `.vbproj` project file:

```xml
<PropertyGroup>
  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
</PropertyGroup>
```

(This shouldn't be necessary if you're using the new SDK project file format, so you can also just convert to that instead.)

**Comment by stakx** [comment] 2018-01-04 21:23
And finally... 🥁

## Regarding Moq, what can be done?

1. What I would like to do first is... nothing, for these reasons:

   * I'd like to see how many people actually run into this problem.
   * I'd like to see whether this problem occurs mostly within the context of ASP.NET. This would indicate that the ASP.NET folks version their assemblies incorrectly. If, however, the problem happens in a lot of different scenarios, then the tooling would be to blame.

2. l'll direct the first few people at the FAQ set up by @JHotterbeekxBannerconnect.

3. Beyond that, if more complaints keep rolling in, I might remove support for `ValueTask<>` and `ValueTuple<>` from Moq's `net45` target. It's pretty much the only possible fix until enough time has passed for people to upgrade their tools and projects to a working combination of NuGet / MSBuild / VS.

I am open to suggestions how to resolve this in a better way.

**Comment by AdamDotNet** [comment] 2018-01-04 21:51
@stakx - I think for now your suggestion of wait and see a little longer probably best. The "holy grail" of .Net Standard sounded really cool until it all fell apart in actual use (in .Net Framework). System.Net.Http is probably the biggest offender, as you've found out. I can't find the war story that came to mind, but it was bad...

A possible solution is to create a Moq.Extensions NuGet. Then treats like ValueTask<T> can be opt in rather than everyone just gets it.

**Comment by stakx** [comment] 2018-01-04 22:16
@AdamDotNet, thanks for this feedback, it's much appreciated. Wait a little longer it is, then!

> A possible solution is to create a Moq.Extensions NuGet. Then treats like ValueTask can be opt in rather than everyone just gets it.

This is a pretty good idea! We just might do that if things don't get better soon. Thank you for suggesting it! (And, if you'd like to contribute by moving the offending bits into a separate package, let me know. I could signal you when the time's right.)

**Comment by AdamDotNet** [comment] 2018-01-04 22:24
@stakx  - I could probably find time to create a new project in the Moq solution and move things over (a list of exactly what you want moved over would be appreciated, if more than just ValueTask). I'm not familiar with how you configure the build server script though.

**Comment by stakx** [comment] 2018-01-04 23:04
@AdamDotNet - If it turns out that we actually need to do this in order to resolve the issue in a clean fashion, I'd be happy to guide you. Adding another project and `.nupkg` to the build script should be fairly straightforward. kzu *might* have to set up a new API key on NuGet, not sure about that. Let's wait a bit longer and worry about the details if and when we actually get that far... agreed?

**Comment by stakx** [comment] 2018-01-07 17:01
@AdamDotNet: It has belatedly occurred to me that moving all `ValueTask<>` and `ValueTuple<>` related functionality to a separate assembly / package isn't actually feasible. This would work for extension methods, such as this one:

https://github.com/moq/moq4/blob/cf10cdb0f220eb3551a8dc451ac94a6f0dc06439/Source/ReturnsExtensions.cs#L35-L38

but it wouldn't work in other cases such as here:

https://github.com/moq/moq4/blob/cf10cdb0f220eb3551a8dc451ac94a6f0dc06439/Source/LookupOrFallbackDefaultValueProvider.cs#L79-L93

without creating a module initializer (global static constructor) which C# does not support, so I fear an extension NuGet package is no way out of DLL hell. :-/

**Comment by tothdavid** [comment] 2018-01-08 16:50
Hi,

We are also affected by this issue. 

So I would like to have a short question: As I can see System.Threading.Tasks.Extension 4.3.0 version package does have net45 target. Could it be a short-term solution to downgrade to 4.3.0 as a dependency to Moq? Probably it would solve this issue as .net core assemblies would not be copied to the build target so the version clash would not happen.
I tried cloning the repo and downgrading the package and it seems like after a successful build all the tests pass. Obviously I am not familiar with the Moq solution and tooling so there may be some issue that I can't see.

Thanks,
David

**Comment by stakx** [comment] 2018-01-08 17:51
> As I can see System.Threading.Tasks.Extension 4.3.0 version package does have net45 target.

Not quite correct, as I came to realize a little later: It does target .NET Framework 4.5 via Portable Class Library. But the build targets will obviously not pick that one, but favour the .NET Standard TFM instead.

> Could it be a short-term solution to downgrade to 4.3.0 as a dependency to Moq?

I don't think so, because 4.3.0 also targets .NET Standard 1.0, and at this point I suspect that the build targets will favour that one over the explicit .NET 4.5 TFM. It might be worth a try, even though it means that everyone who has .NET Core 2.0 build tools installed will then get upgrade warnings.

> I tried cloning the repo and downgrading the package and it seems like after a successful build all the tests pass. Obviously I am not familiar with the Moq solution and tooling so there may be some issue that I can't see.

Moq's own test already pass, or it wouldn't have been published. No need for you to test this. The question is whether *your* projects' tests will pass when you use a custom-built version of Moq that targets 4.3.0 of the STTE package? Is this what you tried?

At the end of the day, this is really Microsoft's problem to solve. Moq's only choices at present are (as far as I can see):

1. Whether to offer support for `ValueTask<>` and `ValueTuple<>`.
2. If so, whether to offer it for all targeted platforms (`net45` and `netstandard1.3`) or just for the latter (`netstandard1.3`).

**Comment by AdamDotNet** [comment] 2018-01-08 17:57
@stakx - Maybe this is over-engineering it a bit, but we could make a "plugin" system in order to do a module load.

1. Moq looks for IMockModule in the bin folder - could be slower because it would check all of the user's dlls too. But can be considered a user extension point. Could be configurable and is off by default.
2. Moq looks for "known" extension dlls only, should be faster.

With either choice, Moq does not fail to start if no IMockModules are found. The IMockModule has the methods needed to bootstrap like you showed with LookupOrFallbackDefaultValueProvider.cs.

The cons are fairly bad though, in my opinion: start up time slowed down, complicated code, etc.

**Comment by stakx** [comment] 2018-01-08 18:09
@AdamDotNet - The biggest con in my opinion is the fact that a plugin system wouldn't be needed under normal circumstances. If we add a plugin system now, just to circumvent a .NET tooling issue, we'll have to maintain it. I'd say, let's not rush things.

I usually try to refrain from ranting and voicing my personal opinion too loudly, but I have becoming quite disillusioned with the .NET ecosystem lately. One of the beauties of the .NET Framework used to be the rock-solid tooling. .NET is now open-source and cross-platform and cool, but this has come at the expense of reliability. I've seen several such hiccups in just the past 6 months, and each time Microsoft expects the community to jump through hoops and reconfigure their builds just to keep things working. I'm not sure how much longer I'm ready to keep participating in this circus.

Sorry for the rant.

**Comment by stakx** [comment] 2018-01-08 19:09
@tothdavid - you might just have saved everyone's day! 👏

I have tried what you suggested and downgraded `System.Threading.Tasks.Extensions` to 4.3.0. Other people's mileage may vary, but on my developer machine and with a simply repro project, this results in NuGet picking the .NET Framework-specific assembly over the .NET Standard one, meaning MSBuild *won't* copy dozens of .NET Standard shim DLLs to the output directory, which in turn means less assembly version conflicts. I'll look into this some more, then release an updated version of Moq.

**Comment by tothdavid** [comment] 2018-01-08 21:08
@stakx thanks, you are great. I will upgrade to the new version tomorrow.
Actually I did try earlier to install STTE 4.3.0 package instead of 4.4.0 following your example which did not include Moq as a dependency at all and it worked here as well.

**Comment by stakx** [comment] 2018-01-08 21:16
Just pushed Moq version 4.8.1 to NuGet with depends on an earlier release of `System.Threading.Tasks.Extensions` as suggested by @tothdavid.

Everyone, could you please test whether 4.8.1 fixes the problem? You should temporarily disable the fix that you might have applied earlier; that is, temporarily set `<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>` in the project file or remove the setting altogether if you've added it before.)

(You might be surprised to see that Moq 4.8.1 additionally depends on `System.ValueTuple`. This might seem counterproductive. But if we want Moq to have `ValueTuple<>` support, we'd eventually have to add this dependency anyway and I'd rather get it over with now than having to repeat the same problem next time around.)

**Comment by tothdavid** [comment] 2018-01-09 10:35
@stakx I can confirm, the new version fixes the issue (at least for me). The ValueTuple dependency also did not introduce any similar problem.

**Comment by JHotterbeekxBannerconnect** [comment] 2018-01-10 07:45
@stakx It seems to work in the test project that I created, however I am having troubles getting it to work in our main project. When removing Moq, with dependencies and afterwards installing version 4.8.1, I can see that System.Threading.Tasks.Extensions and System.ValueTuple are now 4.3.0. However trying to run any test now results in the following error:

```
System.TypeInitializationException : The type initializer for 'Moq.DefaultValueProvider' threw an exception.
  ----> System.IO.FileLoadException : Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

And I haven't been able to figure out the cause for this error.

**Comment by stakx** [comment] 2018-01-10 07:48
@JHotterbeekxBannerconnect, I suppose you've already made sure that you're working with a clean output directory. Can you provide a small test code for the problem you're seeing now?

**Comment by JHotterbeekxBannerconnect** [comment] 2018-01-10 07:51
@stakx Yes, everything has been cleaned before running the tests. I'll going to try and find some room in the next days to reproduce this on a smaller scale.

**Comment by stakx** [comment] 2018-01-11 08:50
See also https://github.com/moq/moq4/issues/567#issuecomment-356641367.

**Comment by rikrak** [comment] 2018-01-12 17:20
@JHotterbeekxBannerconnect Not sure if this is relevant to your situation, but I had to clear out and amend a load of assembly redirects from the test project's app.config after installing v4.8.1 of Moq.  Essentially I had a rogue redirect:
`      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>`
Which should be:
`      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" />
      </dependentAssembly>`

The difference being in the version numbers

**Comment by JHotterbeekxBannerconnect** [comment] 2018-01-17 12:26
@rikrak Thanks for the hint! @stakx I've got it working in solution as well. It did take some work, but eventually I just removed Moq, and it's dependencies. Cleared the line which @rikrak pointed out and installed the latest version of Moq, now everything works fine. Thanks for all the trouble!

**Comment by stakx** [comment] 2018-01-17 12:40
It appears that everyone in this thread who has reported having this issue now got things working, with the exception of @clottman, who hasn't yet responded. I'd like to close this issue for now. If the problem surfaces again, or we get more repro code here, I'm happy to reopen.

**Closed by stakx** 2018-01-17 12:40 UTC
Labels: needs-repro

**Comment by robbihun** [comment] 2018-01-24 22:16
I'm receiving the same error with Moq nuget package 4.8.1 in a .net 4.6.2 test project.

Was able to work around it by modifying the .csproj file and  changing the reference path from the netstandard2.0 folder to the net462 folder for SystemValue Tuple and from the netstandard1.0 to portable-net45+win8+wp8+wpa81 for System.Threading.Tasks.Extensions.

```
    <Reference Include="System.Threading.Tasks.Extensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Threading.Tasks.Extensions.4.4.0\lib\portable-net45+win8+wp8+wpa81\System.Threading.Tasks.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>..\packages\System.ValueTuple.4.4.0\lib\net461\System.ValueTuple.dll</HintPath>
    </Reference>
```

**Comment by stakx** [comment] 2018-01-25 06:02
@robbihun: The problem likely is no longer Moq but your using versions 4.4.0 of these two System packages. Try downgrading them to 4.3.0.

**Comment by rhyous** [comment] 2018-02-20 18:03
Did anyone submit a bug with System.Threading.Tasks.Extensions.4.4.0 to get a fix for this issue? 
Or is there a workaround for this breaking change?

**Comment by stakx** [comment] 2018-02-20 18:28
> Did anyone submit a bug with System.Threading.Tasks.Extensions.4.4.0 to get a fix for this issue?

If any one particular package is versioned incorrectly, it would likely be System.Net.Http. But the real problem isn't with any one specific package, IMHO, but the fact that .NET 4.6.1 has been changed retroactively to support and prefer .NET Standard 2.0 over portable libraries, thereby resulting in conflicts between framework DLLs and differently-versioned .NET Standard shim DLLs being copied over to your project's output directory.

> Or is there a workaround for this breaking change?

See above: https://github.com/moq/moq4/issues/566#issuecomment-355222021.

> This workaround to manually edit the csproj to use the portalable library in the NuGet package worked for me.

Glad you found a solution that works for you. But your manual changes will probably be overwritten next time you upgrade packages.

**Comment by rhyous** [comment] 2018-02-20 18:39
> If any one particular package is versioned incorrectly, it would likely be System.Net.Http.

I didn't think System.Net.Http was even a package involved, as it is not an installed NuGet package. However, taking into account .NET Standard shim DLLs, this makes sense. The System.Net.Http objects could be seen as completely different object in the shims.

> Glad you found a solution that works for you. But your manual changes will probably be overwritten next time you upgrade packages.

Exactly why I want to follow this up. I would love for my manual changes to be overwritten AND the bug to be fixed and not notice this when the next version comes out.

**Comment by stakx** [comment] 2018-02-20 19:02
> Exactly why I want to follow this up.

I understand. Unfortunately, there's not much we can do here at the Moq project other than fixing #578.

I suggest you take this up directly with the .NET team. Like I said above, please see the issue I linked to in the comment above (https://github.com/dotnet/standard/issues/481). To be very honest with you, I am really quite fed up with (and burned out a little due to) the .NET assembly versioning mess that's been going on for the past few years, so please don't count on my support. :-/

I sincerely do hope, however, that if you follow up on this, that you'll be successful in getting this through to Microsoft.

**Comment by stakx** [comment] 2018-02-20 19:27
P.S.:

> Unfortunately, there's not much we can do here at the Moq project other than fixing #578.

I should've asked earlier, but: Do you disagree with me? Is there something we missed & still go about in the wrong way at Moq, regarding these System NuGet package references? If so it'd be great to hear about it.

**Comment by ManfredLange** [comment] 2018-03-17 19:41
Further to this: I am receiving this problem with a project in new csproj format targeting net461. Although not required, I tried it with and without the workaround adding properties `AutoGenerateBindingRedirects` and `GenerateBindingRedirectsOutputType`. No success either way. Up to now we used Moq version 4.7.8 which worked. We are trying to upgrade to Moq version 4.8.2. This also upgrades Castle.Core from version 4.0.0 to version 4.2.1.

Since we have 50+ projects with test in them switching mocking frameworks would be an expensive/risky exercise which obviously we would like to avoid.

Anyone has any other suggestion for what we could try to resolve this issue?

**Comment by ManfredLange** [comment] 2018-03-19 19:33
@rhyous Thank you for the suggestion. We found a work around. We were using Moq to mock HttpResponseBase, HttpRequestBase and HttpContextBase. We now have our own explicit mocks in place for these. We have almost 60 projects in our solution so going back and forth between different versions of 3rd party libraries has its limitations both technically and time wise. We appreciate that it seems to a be an issue within dotnet and unrelated to Moq. In our case it appeared when we upgraded Moq. We acknowledge that it's not caused by Moq.

We continue to use Moq for almost all our mocking needs, so please keep up the excellent work on this project. Thank you!

**Comment by stakx** [comment] 2018-03-19 19:49
@ManfredLange - Thanks for the kind words. May I suggest that you watch #605 if you're still interested in seeing this resolved? It's likely that we'll soon add .NET Standard 2.0 as a framework target to the Moq NuGet package. I haven't carved out an exact plan yet, but adding direct support for .NET Standard 2.0 will likely mean, among other things, less NuGet package dependencies. If we update Moq's dependency on System.Threading.Tasks.Extensions to package version 4.4.0, then Moq should no longer bring in the System.Net.Http package via System.Runtime into your projects. I'm not sure if it'll work out like that in your case (you might have to update the problematic unit test projects to .NET 4.7), but it's perhaps worth a try.

**Comment by ManfredLange** [comment] 2018-03-19 22:11
@stakx We are migrating our projects across from net461 to netstandard2.0 / netcoreapp2.0 at the moment. For that process we believe that going to .NET 4.7, then to netstandard2.0 would be more of a sidetrack. We are happy to continue use Moq. We always knew that mocking HttpRequestBase, HttpResponseBase and HttpContextBase could be a stretch. And mocking of these classes will change with ASP.NET Core MVC again as far as we know.

We are definitely looking forward to netstandard2.0 support for Moq. :-)

**Comment by willapp** [comment] 2018-03-21 16:08
I see this is a very long thread and apologies I didn't read every single post, but I have just been bitten with what appears to be the same issue upgrading from 4.7.145.0 to 4.8.0.0, although getting a different error when running some unit tests:

`System.TypeInitializationException : The type initializer for 'Moq.DefaultValueProvider' threw an exception.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

This is in a .Net Framework 4.5 assembly and is fixed by reverting back to 4.7.145.0 and removing the `System.Threading.Tasks.Extensions` nuget package so I can only assume it's related.

I know Moq is a community project but it would be nice if this breaking change had been made into a major version update so we could be a bit more confident that a minor release won't break our projects.

**Comment by stakx** [comment] 2018-05-07 16:16
@AdamCaviness - people keep having problems with this... and I almost can't quite believe that tooling is indeed so broken that there's no way at all to work around this. Would it be possible for you to submit a small test project (e.g. as a ZIP file) for me to look at?

**Comment by AdamCaviness** [comment] 2018-05-07 19:03
@stakx Because our solutions are so large I should have started with a sample project really. As I began to consider the requirements for a sample project I discovered that one of my three lower-level test projects had no app.config file and hence no binding redirects. This of course sorted it out. For the curious, I was able to keep all the project references to the assemblies pointing to netstandard2.0 instead of portable-net45+win8+wp8+wpa81. I was also able to keep my framework version at 4.7 and I didn't need 4.7.2.

**Comment by stakx** [comment] 2018-05-07 19:18
@AdamCaviness - great to hear you were able to sort things out!

**Comment by skram-softheme** [comment] 2018-06-26 13:13
We are having same issue with 4.8.3 on .net 4.6.2, have to downgrade to 4.7.145.

**Comment by stakx** [comment] 2018-06-26 13:28
@skram-softheme ... or resolve the version conflict. It's usually very much possible. :wink:

**Comment by MarcosMeli** [comment] 2018-07-07 16:54
We solved the problem in TeamCity setting the advance setting Path to application configuration file: 

![image](https://user-images.githubusercontent.com/446796/42412962-1b6fc146-81ed-11e8-89f4-a911fb565570.png)

The config file contains the binding redirect:

      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />
      </dependentAssembly>

**Comment by DianaKoenraadt** [comment] 2019-12-10 14:48
For anyone encountering this issue in 2019. The tests ran successfully (green) on our development environment. However, they failed on the build server with

```
System.TypeInitializationException : The type initializer for 'Moq.DefaultValueProvider' threw an exception.
  ----> System.IO.FileLoadException : Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  ----> System.IO.FileLoadException : Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Moq.Mock`1..ctor(MockBehavior behavior, Object[] args)
   at SomeTest() in SomeTest.cs:line 16
--FileLoadException
   at Moq.LookupOrFallbackDefaultValueProvider..ctor()
   at Moq.EmptyDefaultValueProvider..ctor()
   at Moq.DefaultValueProvider..cctor()
--FileLoadException
```

Adding the Binding nodes to the PropertyGroup didn't work for me. I ended up updating System.Threading.Tasks.Extensions separately. The tests are now green on our build server as well.

**Comment by sdebruyn** [comment] 2020-01-22 14:46
hi @DianaKoenraadt, could you elaborate on how did that?

**Comment by woutermeuwis** [comment] 2020-01-27 15:23
@sdebruyn 
> 4.7.145

Seems to fix it

**Comment by rubixxcube** [comment] 2020-03-26 01:21
> hi @DianaKoenraadt, could you elaborate on how you did that?

I just ran into the same issue and resolved it using @DianaKoenraadt's method, basically after updating to the latest version of MOQ, go the manage nuget packages->installed tab and you will see a package for 
![image](https://user-images.githubusercontent.com/6234642/77600497-86b49c80-6ede-11ea-99d4-59065970eb91.png)

If it is not the latest click the Update button on the right to update to the latest, this is what i did and after doing so everything worked.  I am using VS2019.

**Comment by PawKanarek** [comment] 2020-06-09 10:35
Im Using <PackageReference Include="Moq" Version="4.13.1" /> and still encounter this problem
