### ISSUE TITLE
Moq.SetupGet doesn't work with Mock.Of<>

### ISSUE THREAD

**Issue by MatthiasLaroche** [moq/moq4#526] opened 2017-11-21 01:16 UTC
When a mock is created with new Mock<>, a getter can be modified with SetupGet.
When a mock is created with Mock.Of<>, SetupGet doesn't seem to work.

Code sample :

        public static void Test()
        {
            var mockConnection1 = new Mock<EntityConnection>();
            var connection1 = mockConnection1.Object;
            mockConnection1.SetupGet(c => c.ConnectionString).Returns("_");

            var connection2 = Mock.Of<EntityConnection>();
            var mockConnection2 = Mock.Get(connection2);
            mockConnection2.SetupGet(c => c.ConnectionString).Returns("_");

            Assert.Equal("_", connection1.ConnectionString); // OK
            Assert.Equal("_", connection2.ConnectionString); // "_" != null
        }

I'm using nuget 4.7.145

**Comment by stakx** [comment] 2017-11-21 08:45
> `"_" != null`

I take this to mean that the second assertion fails because the actual value returned from `connection2` equals `null`. Correct?

I cannot reproduce that issue given Moq 4.7.145, your test code, and either of the following definitions for `EntityConnection`:

```csharp
public interface EntityConnection
{
    string ConnectionString { get; set; }
}
```

```csharp
public interface EntityConnection
{
    string ConnectionString { get; }
}
```

```csharp
public abstract class EntityConnection
{
    public virtual string ConnectionString { get; }
}
```

Could you please update your repro code to be minimally complete (i.e. include the relevant parts of the type that you're mocking), and so that it reproduces the issue you're describing?

**Comment by stakx** [comment] 2017-11-21 09:16
Could reproduce the problem with the following type definition:

```csharp
public abstract class DbConnection
{
    public abstract string ConnectionString { get; set; }
}

public class EntityConnection : DbConnection
{
    public override string ConnectionString { get; set; }
}
```

I can confirm that this issue has already been fixed in the `develop` branch (most likely thanks to #509), so your scenario will work fine with the upcoming version of Moq.

**Closed by stakx** 2017-11-21 09:16 UTC
