### ISSUE TITLE
Test method throw exeption Castle.DynamicProxy.ProxyGenerationException

### ISSUE THREAD

**Issue by Shifty15** [moq/moq4#941] opened 2019-10-17 08:00 UTC
Hi,
I'm using Moq, recently we start using "in" as modificator for parameters in methods and our test failed on this exception. 
I did small project where I reproduce it (ConsoleApp3.zip). Problem seems to be when I'm trying get moq.Object. 

We are using:
MS Test
.NET Framework 4.7.2
Moq 4.13.0
Castle.Core 4.4.0

Stack trace:
Castle.DynamicProxy.ProxyGenerationException: There was an error in static constructor on type Castle.Proxies.TestInterface`1Proxy. This is likely a bug in DynamicProxy. Please report it. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Castle.Proxies.TestInterface`1Proxy' threw an exception. ---> System.MissingMethodException: Method not found: 'Int32 ConsoleApp3.TestInterface`1.GetValueWithIn(Int32 ByRef, Boolean)'.

[ConsoleApp3.zip](https://github.com/moq/moq4/files/3738008/ConsoleApp3.zip)

**Comment by stakx** [comment] 2019-10-17 08:18
Hi @Shifty15, as you can see in the exception message, this is an error thrown by DynamicProxy (which Moq uses). Your issue is a duplicate of https://github.com/castleproject/Core/issues/430. I'll close this issue as the bug has to be fixed somewhere else (in the .NET / .NET Core runtimes)... nothing we can do about this in Moq.

**Closed by stakx** 2019-10-17 08:18 UTC
