### ISSUE TITLE
Using ref in .Callback

### ISSUE THREAD

**Issue by davweiss** [moq/moq4#305] opened 2016-12-02 08:33 UTC
Hello,

I have a little problem with ref Parameters in .Callback.

Here is the Code:
`
short o = 0;
r => r.testFunction(It.IsAny<ushort>(), It.IsAny<short>(), ref o, It.IsAny<ODBEXAXISNAME>()))
                .Callback<ushort, short, short, ODBEXAXISNAME>((hndl, typ, nu, axnam) =>
                {
                    ...
                });
`
![callbackwithref](https://cloud.githubusercontent.com/assets/20642456/20827415/1b98c49c-b872-11e6-9db0-f96f60809f98.png)

trows the exception:

> An exception of type 'System.ArgumentException' occurred in Moq.dll but was not handled in user code
>Additional information: Invalid callback. Setup on method with parameters (UInt16,Int16,Int16&,ODBEXAXISNAME) cannot invoke callback with parameters (UInt16,Int16,Int16,ODBEXAXISNAME).
![callbackexception](https://cloud.githubusercontent.com/assets/20642456/20827428/28b5df3e-b872-11e6-8d6c-16ba5526f1b5.png)

If i want to add ref in Callback the code wont compile:
![callbackwithref](https://cloud.githubusercontent.com/assets/20642456/20827450/50f342ac-b872-11e6-900b-74f3e57374da.png)

Can you help me/ tell me how to test this function?

**Comment by AdrienPoupa** [comment] 2017-06-20 12:55
Duplicate of #105

**Comment by stakx** [comment] 2017-06-27 06:05
@davweiss: Currently, Moq doesn't support `ref` / `out` parameters in `Callback`. Please subscribe to the issue @AdrienPoupa linked to above (#105) if you're still interested in seeing this problem resolved. I'm planning to look at this in the next few weeks.

**Closed by stakx** 2017-06-27 06:05 UTC
Labels: duplicate
