### ISSUE TITLE
IsAny() not matching where it should?

### ISSUE THREAD

**Issue by jez9999** [moq/moq4#1020] opened 2020-05-19 18:37 UTC
So I've been trying to verify if my .NET Core 3 `ILogger` mock has been called in my Assert phase, and the following successfully throws if my test method logs an error or a critical:

```
    _weatherLoggerMock.Verify(logger => logger.Log(
        It.IsIn(new LogLevel[] { LogLevel.Error, LogLevel.Critical }),
        It.IsAny<EventId>(),
        It.IsAny<It.IsAnyType>(),
        It.IsAny<Exception>(),
        It.Is<Func<It.IsAnyType, Exception, string>>((v,t) => true)
    ), Times.Never(), "Logger was called with Error or Critical!");
```

However, the following doesn't throw:

```
    _weatherLoggerMock.Verify(logger => logger.Log(
        It.IsIn(new LogLevel[] { LogLevel.Error, LogLevel.Critical }),
        It.IsAny<EventId>(),
        It.IsAny<It.IsAnyType>(),
        It.IsAny<Exception>(),
        It.IsAny<Func<It.IsAnyType, Exception, string>>()
    ), Times.Never(), "Logger was called with Error or Critical!");
```

Is this correct behaviour?  It looks like the two should be semantically identical; in both cases I'm saying that the parameter should match the given type, and match no matter what the value.  Why doesn't `IsAny` match?

**Comment by stakx** [comment] 2020-05-19 20:34
See #919 and the `ILogger`-related linked there.

**Comment by jez9999** [comment] 2020-05-19 20:42
> 
> 
> See #919 and the `ILogger`-related linked there.

I did read that but I don't quite see how it answers this issue?  The solution there can't use IsAny() either.

**Comment by stakx** [comment] 2020-05-19 21:12
Again, very likely because of the nested `It.IsAnyType`. Have you seen https://github.com/moq/moq4/issues/918#issuecomment-527647423?

**Comment by jez9999** [comment] 2020-05-20 07:42
Ah ok, I see now.

**Comment by stakx** [comment] 2020-05-21 05:33
I'll close this as a duplicate of #918. If you think that's in error please post here again.

**Closed by stakx** 2020-05-21 05:33 UTC
Labels: duplicate, question
