### ISSUE TITLE
It.IsAny<decimal> throws "System.decimal is not a supported constant type"

### ISSUE THREAD

**Issue by dinismvcorreia** [moq/moq4#265] opened 2016-05-30 10:45 UTC
I was using Moq 4.5.3. and decided to update Moq Nuget package to the latest version, which is 4.5.8.
Suddenly, a lot of my tests started to fail. I found that the issue occurs when using `It.IsAny<decimal>` on decimal optional arguments. It throws "System.decimal is not a supported constant type". It also happens in version 4.5.7.
Simple, silly test:

```
public interface IFoo { bool Method(decimal decimalArg = 0m); }

public class Some
{
    public int SomeMethod(IFoo foo) => foo.Method(10m) ? 1 : 0;
}

[TestFixture]
public class SomeTests
{
    [Test]
    public void SampleTest()
    {
        var fooMock = new Mock<IFoo>();
        fooMock.Setup(m => m.Method(It.IsAny<decimal>())).Returns(true);

        var sut = new Some();
        var actual = sut.SomeMethod(fooMock.Object);

        Assert.That(actual, Is.EqualTo(1));
    }
}
```

**Comment by dinismvcorreia** [comment] 2016-05-30 11:48
To easily reproduce the issue, below is a complete simple, silly test:
```
public interface IFoo { bool Method(decimal decimalArg = 0m); }

public class Some
{
    public int SomeMethod(IFoo foo) => foo.Method(10m) ? 1 : 0;
}

[TestFixture]
public class SomeTests
{
    [Test]
    public void SampleTest()
    {
        var fooMock = new Mock<IFoo>();
        fooMock.Setup(m => m.Method(It.IsAny<decimal>())).Returns(true);

        var sut = new Some();
        var actual = sut.SomeMethod(fooMock.Object);

        Assert.That(actual, Is.EqualTo(1));
    }
}

```

**Comment by kzu** [comment] 2016-05-30 11:49
Closed? Why?

**Comment by dinismvcorreia** [comment] 2016-05-30 11:52
Sorry, kzu, my bad. Pressed the wrong button. Anyway, I've edited the initial issue. Now, with the code sample I've supplied, it's easier to reproduce the issue.

**Comment by richardlawley** [comment] 2016-05-31 06:50
The bug actually occurs when the object is constructed, therefore a much simpler repro is:

	public interface IFoo { bool Method(decimal decimalArg = 0m); }

	[TestClass]
	public class SomeTests
	{
		[TestMethod]
		public void SampleTest()
		{
			var fooMock = new Mock<IFoo>();
			var sut = fooMock.Object;
		}
	}

**Comment by richardlawley** [comment] 2016-05-31 06:56
As mentioned in this [SO post](http://stackoverflow.com/a/37533491/163495), this is related to a Castle Core bug: https://github.com/castleproject/Core/issues/87

**Comment by kzu** [comment] 2016-06-01 13:01
Si what are we missing? A dependency bump only? PR? ;)

**Comment by MichaelLogutov** [comment] 2016-06-07 19:36
Any news on that? We're facing false negatives all around :)

**Comment by dampee** [comment] 2016-07-07 22:04
Has anyone found a solution for this?

**Comment by i4004** [comment] 2016-07-08 02:39
@dampee You can use alpha version of Moq (4.5.10 and above).

**Comment by dampee** [comment] 2016-07-08 07:14
@i4004 thanks.  I have reverted to 4.2 yesterday.  Can't upgrade to prerelease versions currently.  Looking forward the the release.

**Comment by brianbegygr** [comment] 2016-09-07 14:33
Any update on this issue?

**Comment by tidusjar** [comment] 2016-09-08 14:50
I've just run into this issue. 😢

**Comment by pipelf** [comment] 2016-10-11 20:20
same problem here.

**Comment by jaredpar** [comment] 2016-11-18 17:09
I hit what I believe is a similar issue trying to mock some Visual Studio Interfaces:

> System.Runtime.InteropServices.DispatchWrapper is not a supported constant type.

It does appear to be a dupe of the castle bug: https://github.com/castleproject/Core/issues/87

In my tests I was able to work around this by upgrading the Castle NuGet package to 4.0.0-beta002.

**Comment by kzu** [comment] 2017-02-21 21:07
We've now bumped to Castle 4.0 stable, so it should be fixed

**Closed by kzu** 2017-02-21 21:07 UTC
