### ISSUE TITLE
Repos\moq4\tests\Moq.Tests\MatchExpressionFixture.cs:row 21

### ISSUE THREAD

**Issue by connywesth** [moq/moq4#828] opened 2019-05-12 09:50 UTC
This is an errormessage I got out-of-the-box when i run run moq.tests in Visual Studio Community 2017. I have just downloaded the latest version from GitHub (May 12, 2019).
![MoqErroeSnapShot](https://user-images.githubusercontent.com/3123534/57580601-05157500-74ac-11e9-9d3b-146c2a291403.JPG)

ERROR MESSAGE (Some phrases translated from Swedish to English for clarity):
Test Name:	Moq.Tests.MatchExpressionFixture.Prevents_compilation
Test FullName:	Moq.Tests.MatchExpressionFixture.Prevents_compilation
Test Source:	F:\Timecut\Repos\moq4\tests\Moq.Tests\MatchExpressionFixture.cs : line 17
Test Outcome:	Failed
Test Duration:	0:00:00,031

Result StackTrace:	
vid Xunit.Assert.Contains(String expectedSubstring, String actualString) i C:\Dev\xunit\xunit\src\xunit.assert\Asserts\StringAsserts.cs:row 22
   vid Moq.Tests.MatchExpressionFixture.Prevents_compilation() i F:\Repos\moq4\tests\Moq.Tests\MatchExpressionFixture.cs:row 21
Result Message:	
Assert.Contains() Failure
Not found: reducible
In value:  must be a  reduceable node

**Comment by stakx** [comment] 2019-05-12 14:13
> Some phrases translated from Swedish to English for clarity

Unfortunately, this obscures the precise cause of the error you're reporting:

> Not found: reducible
> In value: must be a reduceable node

Was the last line translated by you? What was the original error message?

If the error is caused by a Swedish installation of .NET, which reports errors in the Swedish language, do you have any suggestions how to deal with this error source in general (other than simply not testing the messages at all)?

**Comment by stakx** [comment] 2019-05-27 15:50
Closing to due lack of a response.

**Closed by stakx** 2019-05-27 15:50 UTC
