### ISSUE TITLE
API test throws error after upgrade to 4.8.1

### ISSUE THREAD

**Issue by martinRocks** [moq/moq4#581] opened 2018-01-23 20:09 UTC
I'm writing a web application using VS 2017 15.5.4.  I was using Moq 4.7.145 and everything was working just fine in the project.  The project is built on framework 4.7.0.  However, after I upgraded to Moq 4.8.1 and upgraded the System.Threading.Tasks.Extensions to 4.4.0 and System.ValueTuple to 4.4.0 I get the below error.
`Test method Sample.Web.Tests.Controllers.Api.DataControllerTests.GetTest threw exception: 
System.MissingMethodException: Method not found: 'System.Net.Http.HttpResponseMessage Sample.Web.Controllers.Api.DataController.Get()'.
    at Sample.Web.Tests.Controllers.Api.DataControllerTests.GetTest()`

The test that doesn't work is a web API that returns a HttpResponseMessage.  I think the problem is the web project is using 4.0.0 of System.Net.Http.dll and the test project is using 4.2.0.

Also, if I don't upgrade System.Threading.Tasks.Extensions and System.ValueTuple, leaving them at version 4.3.0, things seem to work.

**Comment by stakx** [comment] 2018-01-23 20:31
Duplicate of #566.

> after I upgraded to Moq 4.8.1 and upgraded the System.Threading.Tasks.Extensions to 4.4.0

Try downgrading System.Threading.Tasks.Extensions to 4.3.0. That's what we did between Moq 4.8.0 and 4.8.1.

**Closed** 2018-01-23 20:39 UTC
Labels: duplicate

**Comment by martinRocks** [comment] 2018-01-23 20:54
That works, but does that mean I should never update System.Threading.Tasks.Extensions?

**Comment by stakx** [comment] 2018-01-23 21:12
I don't really know what the best approach is.

Please study carefully the two issues I linked to above, but especially https://github.com/dotnet/standard/issues/481.

You *can* upgrade that package, but whether it'll work depends on:

* how your project files were created,
* which framework version you're targeting,
* whether you're using a `packages.config` or `<PackageReference>` to reference NuGet packages,
* what hidden, largely unknown settings (such as `<AutoGenerateBindingRedirects>` and `<GenerateBindingRedirectsOutputType>`) you might have in your project file,
* what assembly binding redirects you might currently have in your `App.config` or `Web.config`,
* and possibly a thousand other variables.

Questions? Please ask Microsoft. They're responsible for bringing DLL hell back to the full .NET Framework with all that .NET Standard nonsense.

(Sorry for the rant, but this versioning mess really makes me angry. My best guess is that you can upgrade these packages if you really need to, but you'll either have to configure assembly binding redirects, or let MSBuild do this automatically via the `<AutoGenerateBindingRedirects>` project file property; see https://github.com/moq/moq4/issues/566#issuecomment-355222021. You can also try upgrading / migrating your projects to .NET 4.7 or .NET Core 2.0.)

**Comment by stakx** [comment] 2018-01-23 21:56
Please direct that question at the .NET team after you've carefully studied https://github.com/dotnet/standard/issues/481. (Note again that the issue you've had was not caused by Moq&mdash;at least not by version 4.8.1. The root cause is much more fundamental than a single library.)

I hate to be intentionally unhelpful, but in my opinion, the .NET team should be made to feel the full weight of the problem, and bear the burden of what that themselves caused. This .NET versioning madness has to stop, and soon.
