### ISSUE TITLE
`ReturnsAsync` support for `Task`

### ISSUE THREAD

**Issue by amosonn** [moq/moq4#794] opened 2019-04-02 13:23 UTC
Currently, all `ReturnsAsync` variants are `ReturnsAsync<TMock, TResult>`, which make the mock return a `Task<TResult>`. I would expect a `ReturnsAsync<TMock>` variant, which lets it return a `Task`, i.e. for methods `async Task ProcessAsync(..)`, we would have `mock.Setup(m => m.ProcessAsync(..)).ReturnsAsync()`. For `ThrowsAsync`, such a variant already exists.

**Comment by stakx** [comment] 2019-04-02 13:49
I might be missing the obvious, but what would be the benefit of that? When setting up methods returning a `Task`, what's keeping you from simply using `Returns`?

```csharp
interface IMockable
{
    Task DoSomethingAsync();
}

var mock = new Mock<IMockable>();
mock.Setup(m => m.DoSomethingAsync()).Returns(async () => ...);
```

(Btw. if we added something at all, it should probably be a `CallbackAsync`, since `Task` methods don't truly produce a result value.)

**Comment by amosonn** [comment] 2019-04-03 09:47
This is mostly for ergonomics and readability. Sure, you could also always use `.Returns(async () => x)` instead of all of the other `.ReturnsAsync(x)` methods, and even `.Returns(async () => { throw Exception(); })` instead of `.ThrowsAsync<Exception>()`. But they exist because tests are more readable with them, and there's no reason for `Task` methods to be left out.

From my point of view, `Task` methods also return a value, which can be either a `void` "OK" value, or an `Exception`. So I would use `ReturnsAsync` if I want the mock to succeed, and `ThrowsAsync` if I want it to throw, just like I would do with a `Task<T>`.

**Comment by stakx** [comment] 2019-04-03 10:07
> So I would use `ReturnsAsync` if I want the mock to succeed

But you wouldn't do the same thing for regular non-async `void` methods, right?

```csharp
mock.Setup(m => m.VoidMethod()).Returns(() => { /* succeeds */ });
```

That pattern doesn't make sense in the non-async case, and it also doesn't make sense in the async case.

**Comment by stakx** [comment] 2019-04-04 11:40
Related: #702.

**Comment by amosonn** [comment] 2019-04-04 13:13
Well, with a `void` method you don't need this, because just `Setup` without `Returns` will work. But for a `Task` (=`Task(void)`) it will break if you don't add `Returns(Task.CompletedTask)`, and `ReturnsAsync()` seems to be clearer.

**Comment by stakx** [comment] 2019-04-04 15:10
If this is in fact the scenario you're talking about, then this issue here is an exact duplicate of #702.

**Comment by stakx** [comment] 2019-04-04 18:47
I'm closing this issue. `ReturnsAsync` for methods returning a `Task` doesn't make setups easier from a purely technical point of view, nor does it make sense semantically. Either use `.Returns(async () => ... )` (which achieves what you're after in a technical sense), or let's work toward `CallbackAsync(() => ...)` (which would be the semantically correct thing).

**Closed by stakx** 2019-04-04 18:47 UTC

**Comment by mnivet** [comment] 2019-10-23 17:04
I can also suggest you to use the  [Moq.SetupAsync](https://github.com/TalentSoft/Moq.SetupAsync) package that provide the SetupAsync method as an extension method to moq 4 (which is the solution to #384 while waiting something native in moq 5 maybe)

This will allow you to write
```
mock.SetupAsync(m => m.DoSomethingAsync());
```
instead of
```
mock.Setup(m => m.DoSomethingAsync()).Returns(Task.CompletedTask);
```

in fact using the `SetupAsync` method will allow you to write your moq code for async method the same way that you are used to with `Setup` method on non async code, except that you specify the async context first, and then use regular, `Returns`, `CallBack` and `Throws` methods.

Under the hood it just a wrapper above the `Setup` method but that do for you multiple tricky things so it feels as easy to write setup for async methods as it is for non async methods.
