### ISSUE TITLE
Support ref structs on mock Setup parameter

### ISSUE THREAD

**Issue by pipe01** [moq/moq4#979] opened 2020-03-25 10:29 UTC
I'm trying to mock a method that takes in a `ref struct` as a parameter, however I cannot use any of the `It` or `Match` methods as they all require generic arguments. Is there any way I could create my own specific matcher from scratch for only my `ref struct` type?

**Comment by stakx** [comment] 2020-03-25 18:22
Duplicate of https://github.com/moq/moq4/issues/829.

`ref struct`s are types that live exclusively on the evaluation stack. Our using DynamicProxy (to intercept calls) means that mock method arguments all get boxed to type `object` (basically to be put in the `IInvocation.Arguments` array)... which doesn't work for stack-only types. So basically, Moq v4 cannot support `ref struct` parameters.

Note that by-ref parameters (i.e. pass-by-reference) of all other types is supported via `It.Ref<T>.IsAny`.

**Closed by stakx** 2020-03-25 18:22 UTC
Labels: duplicate, known limitation
