### ISSUE TITLE
Async Method Support Clean-up

### ISSUE THREAD

**Issue by rbdevr** [moq/moq4#384] opened 2017-06-21 01:41 UTC
Right now, Moq doesn't have a proper support for async methods. There are a few methods giving Moq some Async support. Those are spreaded through out Moq fluentApi like ReturnAsync() and ThrowAsync() but it's not developer friendly.
I suggest to implement FluentApi support for async methods starting from SetupAsync() and expose only async functionality.
At the same time, remove all the async methods from the current Setup().
Let me know your thoughts. Should I do a request pull and start working on it?
Regards

Example:
interface IComponent {
&nbsp;&nbsp;   int Process(int value);
&nbsp;&nbsp;   Task&lt;int&gt; ProcessAsync(int value);
}
componentMock.Setup(I => Process(It.Any&lt;int&gt;()).Return(1);                               // normal method 
componentMock.Setup(I => Process(It.Any&lt;int&gt;()).Throw(new Exception());        // normal method 
componentMock.Setup(I => Process(It.Any&lt;int&gt;()).Callback<int>(i => capt = i); // normal method 
componentMock.SetupAsync(I => ProcessAsync(It.Any&lt;int&gt;()).Return(1);                                // full async support
componentMock.SetupAsync(I => ProcessAsync(It.Any&lt;int&gt;()).Throw(new Exception());          // full async support
componentMock.SetupAsync(I => ProcessAsync(It.Any&lt;int&gt;()).Callback<int>(i => capt = i);   // full async support

**Comment by stakx** [comment] 2017-06-21 06:32
At first glance, and without considering any more use cases involving `Task` / `Task<T>`, this looks like a great idea! 👍

You are welcome to send a PR!

Let me just mention two points that you're probably already aware of:

 * The new, proposed API should be able to cover the same "async" use cases as the present API. It may be more complete, but it shouldn't be less complete.

 * The present API cannot be removed right away. Superseded methods / interfaces can however be marked as `[Obsolete("Replaced by X / Do Y instead.")]` and hidden using `[EditorBrowsable(EditorBrowsableState.Never)]` to guide users towards the new API.

**Comment by stakx** [comment] 2017-06-21 08:01
Some various related things to be tracked along with this issue (I might expand this list later on):

* [ ] https://github.com/moq/moq4/issues/327#issuecomment-306305885

**Comment by robydev** [comment] 2017-06-21 17:50
I've got the basics in place but with two basic methods Setup and SetupAsync it means double the tests.
I'm thinking how to handle unit tests. Duplicate everything? use template to generate tests for sync or async? or share Setup code with SetupAsync as much as possible, test only Setup and take it for granted? I'm thinking about it.
Any Thoughts?

**Comment by robydev** [comment] 2017-06-22 02:50
I've finished doing some necessary refactoring. I've noticed that it is possible to use Setup() to do normal methods and async methods. .Net is capable to identify one from the other based on the return argument. This makes things a lot easier but there are two things to keep in mind. 
1) It's not implicit that the Setup is a AsyncMethod. This shouldn't matter since it will work both ways. Devs can even change from normal method to async method without having to update the tests. In the other hand since it's not implicit it could cause some misunderstanding. 
2) There will be some compatibility issues(This can be sorted). If the dev update moq in his app. all the Setup used on async methods using ReturnAsync and ThrowAsync will break since I did tag obsolete on ReturnAsync and ThrowAsync but I didn't include in the Setup Async implementation.

**Comment by stakx** [comment] 2017-06-22 07:19
1. (I guess you meant "explicit", not implicit?) Not sure how much confusion additional method overloads would cause here. I tend to think having a slimmer API someday (one method to set up instead of 5, one method for callbacks, one for throws, one for returns) would be a net gain. But I'm not certain at this point.

2. Why would ReturnAsync, ThrowAsync et al. break? That shouldn't happen.

@kzu, what's your opinion on (1) above? Would you prefer full integration of all async setup methods into the regular `Setup`, `Callback`, `Throws`, `Returns` (so there would no longer be a distinction between the sync and async APIs), or would you rather have async setups start with a dedicated `SetupAsync` "entry point" method?

**Comment by robydev** [comment] 2017-06-22 11:42
1) You are correct about the implicit/explicit. I've amended it. 
2) the async Setup() works with ISetupAsync. ReturnAsync() and ThrowAsync() extensions from ISetup. I will have to add them to keep it compatible or force the devs to update their code but I don't think you will agree.
Previously I've mentioned the unittests. What approuch would you prefer?

**Comment by stakx** [comment] 2017-06-22 12:01
Regarding the unit tests, I first need to take a look at what unit tests we are talking about here. I'll get back to you on that!

**Comment by robydev** [comment] 2017-06-22 12:01
All of them I would say.

**Comment by robydev** [comment] 2017-06-22 12:35
1) If there is a need for returning a Task we could have a specific Returns() available only for async Setup() that would allow this scenario. I think implicit is a good choice.
Let me know about the unittests.

**Comment by robydev** [comment] 2017-06-22 15:47
I've found an issue with the ThrowAsync extensions. They are returning IReturnResults&lt;Type&gt; fluentapi interface. It's my understanding they should be returning IThrowResult. 
I've fixed this but please have a look and let me know if this is the correct way to use it.

**Comment by robydev** [comment] 2017-06-23 17:01
I've been struggling to implement the async fluentapi due to the current design. At the same time I've noticed some issues with the fluentapi for sync methods. So I've decided to refactor the method all classes and fluentapi functionality.
It's more work but I think it will solve restrains caused by current design. It's looking good so far.

**Comment by robydev** [comment] 2017-06-23 17:27
I've noticed IOccurrence was decomission and Verify was put in place. Doesn't that break the idea of A clear functionality with FluentApi support?

**Comment by stakx** [comment] 2017-06-27 05:43
Hi @robydev, sorry for not getting back to you sooner. I'm going to set aside some time later this week to look at the work you've done so far, and try to answer your questions. Thanks for being patient!

**Comment by stakx** [comment] 2017-06-27 05:52
Maybe I can answer the occasional question right now:

> I've noticed IOccurrence was decomission and Verify() was put in place. Doesn't that break the idea of a clear Setup() functionality with FluentApi support previously discussed?

Not having the ability to specify a `Times` constraint during setup doesn't necessarily make setup less "clear" (but perhaps I am misunderstanding what exactly you mean by this). See https://github.com/moq/moq4/issues/373#issuecomment-310901103 for a quick explanation why `IOccurrence` was obsoleted.

> I've been struggling to implement the async FluentApi due to the current design. At the same time I've noticed some issues with FluentApi. So I've decided to refactor the methodcall classes and fluentapi functionality. Implementng separation of concerns and giving FluentApi full freedom for future implementations.
> I though about having this work done as a separate issue but it is very difficult to implement async fluentapi without it..
> It's more work but it will solve restrains caused by current design.

I haven't yet looked into the work you've done on this, but generally speaking, you could isolate that refactoring out into a separate PR that precedes the work you're doing on async. If you think keeping those two works separate from one another would help understanding and traceability later on, that would probably be the way to go.

**Comment by rbdevr** [comment] 2018-05-17 17:15
I have checked in the code a long time ago and I didn't hear any feedback.
I have continue working on refactoring fluentapi implementstion but that caused the library to face back compatibility issues.

**Comment by mnivet** [comment] 2018-05-18 15:03
Ok without more reactivity from moq team, let chose to publish an extension package:
https://www.nuget.org/packages/Talentsoft.Moq.SetupAsync/1.0.0

Sources and exemples are here:
https://github.com/TalentSoft/Moq.SetupAsync

**Comment by stakx** [comment] 2018-05-18 15:21
Hi @rbdevr. Your issue is one of the few that sort of fell by the wayside during the issue burnination sprint I did between June 2017 and February 2018. Your issue was/is one with a comparatively large scope, and judging from your own responses (above), it's one that isn't straightforward and demands some potentially tricky decisions. I was simply too busy with other issues back then to allocate more of my own resources for this, so I posted the brief response above, hoping that might get you a little further. I'd like to apologize to you that I didn't communicate better at the time.

Do feel free to keep working on this. However, at present, it might pay off more to direct any improvements at the upcoming version 5 of Moq (https://github.com/moq/moq). Right now, for the time being, Moq 4's API is frozen so Moq 5 can be finalized.

**Comment by mnivet** [comment] 2018-05-22 09:47
OK so I let you work on Moq 5 to integrate a clean SetupAsync with a reworked API.
And for Moq 4 we have the package that already provide something nice to use.

And if final implementation in Moq 5 is not to far from the one in the package, we can hope that migration would be transparent or at least scriptable. I've already write some Roslyn code fix to perform such type of migration. So I'll will keep an eye on your progression to provide such code fix if necessary.

**Comment by stakx** [comment] 2019-10-19 19:17
It has been rather quiet in here for a while. Last time some work was done on this, things turned out to be a little more difficult than expected because of overload conflicts. So for the protocol, if anyone picks this up in the future, here's something to think about:

It might be a good idea to implement a cleaned-up async API as extension methods in a separate namespace, say `Moq.Async`; that way you'd only get the async methods when explicitly importing that namespace.

Another option would be to do something similar as `.Protected()`: you'd have to write `mock.Async()...` to access the async API.

**Comment by mnivet** [comment] 2019-10-23 17:38
> Another option would be to do something similar as `.Protected()`: you'd have to write `mock.Async()...` to access the async API.

And introducing a new `SetupAsync` method like I've done in [Moq.SetupAsync](https://github.com/TalentSoft/Moq.SetupAsync) ?
Why writing `mock.Async()...` would be preferred to writing `mock.SetupAsync()...` ? Is there more than the `Setup` method that need to be specialized for async ?

`SetupGet` and `SetupSet` are not applicable to async (properties could not be async), and `verify` methods do not need to be specialized, since the fact that the method as been called is not linked to the way that the call has been performed.
So maybe it let us `SetupSequence` method in addition to the `Setup`method to cover.

Is that justified to have an `async()` scope method to expose just two methods (`Setup` and `SetupSequence`) dedicated to async instead of having clear overload from the root (`SetupAsync` and maybe a `SetupSequenceAsync`) ?

Furthermore I think that having a scope is less discover-able, than adding a new specialized `SetupAsync` method, since people are use to type Setup, and that intellisence will then show them the `SetupAsync` proposition which may guide them to what they need sooner than trying with the classical Setup, and failing, before looking for that async scope...

For `Protected()`the scope is justified because there is a lot more of methods to expose, and because it's not a basic use case. But working with async methods is a more and more common case, so discover-ability should be take into account in the design of the API in that case.

**Comment by stakx** [comment] 2019-11-02 09:17
>Why writing `mock.Async()...` would be preferred to writing `mock.SetupAsync()...`?

For one thing, because I'd like to avoid new method names. True, in this case it would probably be only `SetupAsync` and `SetupSequenceAsync`, but we'd still be setting up a precedent for future extensions.

Ideally (IMHO), the new methods would be called simply `Setup` (and `SetupSequence` etc.).

Which brings me to the reason I mentioned above: if we went with just `Setup`, we'd need to think about minimizing method resolution conflicts. Moq's fluent API has a lot of method overloads, and there are already situations where things get ambiguous. The more we overload methods, the worse the situation will get, and I'd like to prevent us from painting ourselves into a corner as early on as possible.

That's how and why I ended up thinking about `.Async().Setup`, it fulfills all of the above:

* doesn't introduce new `Setup*` method names
* doesn't increase the risk of method resolution conflicts of existing methods

We could of course do `SetupAsync`, `SetupSequenceAsync` etc. and "hide" them as extension methods in a separate namespace, I simply thought it reasonable to follow the precedent / existing pattern set up by `.Protected()`.

**Comment by stakx** [comment] 2020-04-25 22:09
I'm going to close this issue in favor of #1007. By adding an `await`-like operator to setup expressions & letting the internal machinery transparently handle the necessary return value transformations, there should no longer be any strict need at all for any `SetupAsync` / `ReturnsAsync` / `ThrowsAsync` etc. methods... and thus no need to clean them up.

**Closed by stakx** 2020-04-25 22:09 UTC
