### ISSUE TITLE
Adding a generic ThrowsAsync method

### ISSUE THREAD

**Issue by jehof** [moq/moq4#692] opened 2018-09-14 09:35 UTC
Is it possible to add a generic version of ThrowsAsync like it is available with Throws<T>, so that we could write

`mock.Setup(p => p.DoAsync()).ThrowsAsync<InvalidOperationException>();`

instead of 

`mock.Setup(p => p.DoAsync()).ThrowsAsync(new InvalidOperationException());`

**Comment by stakx** [comment] 2019-02-16 21:17
I've taken a closer look today, and it turns out that this isn't as easy as I thought... more likely, it's not possible to implement this in a useful manner.

The problem is that the extension method for `mock.ThrowsAsync(exception)` is already generic:

https://github.com/moq/moq4/blob/4abde509e4362c16f56b7386d830ea4f4dc7975f/src/Moq/ReturnsExtensions.cs#L73

While we could just have another method extension overload with an additional `TException` generic parameter, that wouldn't be very practical because you'd always have to specify all generic arguments (e.g. `setupOnFooMock.ThrowsAsync<IFoo, SomeException>()` instead of just `setupOnFooMock.ThrowsAsync<SomeException>()`).

So why does the generic argument thingy work with regular `mock.Throws<SomeException>()`? Because that method isn't generic. Instead, the generic parameter sits on the containing interface. Unfortunately, adding `ThrowsAsync` in the same interface isn't an option, because we can only specialize it for `Task` and `ValueTask` return values using extension methods.

So unfortunately, I don't think adding the requested `ThrowsAsync<TException>` overload is worth it because it will result in an impractical API. Because of this, I'm going to close this issue. Sorry for the bad news! 😢

**Closed by stakx** 2019-02-16 21:17 UTC

**Comment by mnivet** [comment] 2019-10-23 09:28
You can use [Moq.SetupAsync](https://github.com/TalentSoft/Moq.SetupAsync) to achieve that, but with a slightly different syntax:

`mock.SetupAsync(p => p.DoAsync()).Throws<InvalidOperationException>();`

The package provide a SetupAsync extension methods, that then provide similar features than the standard Setup method, but we known from the start that we are in an async context which allow to provide the correct implementations for `Task` and `Task<T>`
