### ISSUE TITLE
Setups with Nullable types on strict mocks no longer match null

### ISSUE THREAD

**Issue by pkpjpm** [moq/moq4#184] opened 2015-06-23 21:14 UTC
Here's an example of the problem:

```
        var mock = new Mock<ISimpleInterface>(MockBehavior.Strict);
        mock.Setup(x => x.SimpleMethod(It.IsAny<Guid?>()));
        mock.Object.SimpleMethod(null);
```

This used to work in Moq 4.2.1502.0911, but in 4.2.1506.2016 it fails. Workaround is to setup null explicitly instead of the Nullable Guid:

```
        mock.Setup(x => x.SimpleMethod(null));
```

**Comment by IharBury** [comment] 2015-06-25 09:39
The problem is in https://github.com/Moq/moq4/commit/cc45976c8870322a170fc020a32d9191cc8d33f5 because of Nullable<T> is value type

**Comment by kzu** [comment] 2015-06-25 15:59
So this should also be fixed by the merged PR #185. if so, plz close after verifying :)

**Comment by stakx** [comment] 2017-06-18 15:59
The test at the top of this thread works fine in recent versions of Moq, so I am closing this.

**Closed by stakx** 2017-06-18 15:59 UTC
